<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use App\Models\Job\Company;
use Illuminate\Support\Str;

class CompanySeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $companies = [
            [
                'name' => 'MTN Uganda',
                'slug' => Str::slug('MTN Uganda'),
                'logo' => 'companies/logos/mtn-uganda.png',
                'description' => 'MTN Uganda is the leading telecommunications company in Uganda, providing mobile voice, data, fintech, digital, and enterprise solutions to millions of Ugandans.',
                'website' => 'https://www.mtn.co.ug',
                'contact_name' => 'Sylvia Mulinge',
                'contact_email' => 'info@mtn.co.ug',
                'contact_phone' => '+256312200200',
                'address1' => 'MTN Towers, 22 Hannington Road, Kampala',
                'company_size' => '1000+',
                'industry_id' => 1, // Telecommunications/Technology
                'is_active' => true,
                'is_verified' => true,
            ],
            [
                'name' => 'Airtel Uganda',
                'slug' => Str::slug('Airtel Uganda'),
                'logo' => 'companies/logos/airtel-uganda.png',
                'description' => 'Airtel Uganda is a leading mobile telecommunications company, offering prepaid, postpaid, and 4G internet services across Uganda.',
                'website' => 'https://www.airtel.co.ug',
                'contact_name' => 'Manish Makhija',
                'contact_email' => 'customercare.ug@airtel.com',
                'contact_phone' => '+256312200200',
                'address1' => 'Airtel Towers, 3 Kololo Hill Lane, Kampala',
                'company_size' => '1000+',
                'industry_id' => 1, // Telecommunications/Technology
                'is_active' => true,
                'is_verified' => true,
            ],
            [
                'name' => 'Stanbic Bank Uganda',
                'slug' => Str::slug('Stanbic Bank Uganda'),
                'logo' => 'companies/logos/stanbic-uganda.png',
                'description' => 'Stanbic Bank Uganda is the largest commercial bank in Uganda, offering a wide range of banking and financial services to individuals and businesses.',
                'website' => 'https://www.stanbicbank.co.ug',
                'contact_name' => 'Francis Karuhanga',
                'contact_email' => 'info@stanbic.com',
                'contact_phone' => '+256312224411',
                'address1' => 'Stanbic Bank Building, 17 Hannington Road, Kampala',
                'company_size' => '500-1000',
                'industry_id' => 2, // Banking/Finance
                'is_active' => true,
                'is_verified' => true,
            ],
            [
                'name' => 'Centenary Bank',
                'slug' => Str::slug('Centenary Bank'),
                'logo' => 'companies/logos/centenary-bank.png',
                'description' => 'Centenary Bank is Uganda\'s largest microfinance bank, providing savings and credit services to individuals, small businesses, and agricultural communities.',
                'website' => 'https://www.centenarybank.co.ug',
                'contact_name' => 'Fabian Kasi',
                'contact_email' => 'info@centenarybank.co.ug',
                'contact_phone' => '+256800299299',
                'address1' => 'Centenary House, Plot 4-6 Entebbe Road, Kampala',
                'company_size' => '500-1000',
                'industry_id' => 2, // Banking/Finance
                'is_active' => true,
                'is_verified' => true,
            ],
            [
                'name' => 'Uganda Breweries Limited',
                'slug' => Str::slug('Uganda Breweries Limited'),
                'logo' => 'companies/logos/uganda-breweries.png',
                'description' => 'Uganda Breweries Limited is the oldest brewing company in Uganda, producing popular beer brands like Bell, Nile Special, and Pilsner Lager.',
                'website' => 'https://www.ugandabreweries.com',
                'contact_name' => 'Julian Adyeri',
                'contact_email' => 'info@ugandabreweries.com',
                'contact_phone' => '+256414347000',
                'address1' => 'Port Bell Road, Luzira, Kampala',
                'company_size' => '500-1000',
                'industry_id' => 3, // Manufacturing/FMCG
                'is_active' => true,
                'is_verified' => true,
            ],
            [
                'name' => 'Nile Breweries Limited',
                'slug' => Str::slug('Nile Breweries Limited'),
                'logo' => 'companies/logos/nile-breweries.png',
                'description' => 'Nile Breweries Limited is a major beverage company in Uganda, known for producing Nile Special, Eagle Lager, and Club Pilsner.',
                'website' => 'https://www.nilebreweries.com',
                'contact_name' => 'Isingoma Jackson',
                'contact_email' => 'info@nilebreweries.com',
                'contact_phone' => '+256392200400',
                'address1' => 'Njeru Industrial Park, Jinja',
                'company_size' => '500-1000',
                'industry_id' => 3, // Manufacturing/FMCG
                'is_active' => true,
                'is_verified' => true,
            ],
            [
                'name' => 'Coca-Cola Beverages Africa (Uganda)',
                'slug' => Str::slug('Coca-Cola Beverages Africa Uganda'),
                'logo' => 'companies/logos/coca-cola-uganda.png',
                'description' => 'Coca-Cola Beverages Africa is the largest beverage company in Uganda, manufacturing and distributing Coca-Cola products across the country.',
                'website' => 'https://www.ccbagroup.com',
                'contact_name' => 'Melkamu Terefe',
                'contact_email' => 'info@ccba.ug',
                'contact_phone' => '+256312350000',
                'address1' => 'Namanve Industrial Park, Kampala-Jinja Highway',
                'company_size' => '500-1000',
                'industry_id' => 3, // Manufacturing/FMCG
                'is_active' => true,
                'is_verified' => true,
            ],
            [
                'name' => 'Jumia Uganda',
                'slug' => Str::slug('Jumia Uganda'),
                'logo' => 'companies/logos/jumia-uganda.png',
                'description' => 'Jumia Uganda is the leading e-commerce platform in Uganda, offering a wide range of products including electronics, fashion, and home goods.',
                'website' => 'https://www.jumia.ug',
                'contact_name' => 'Tesh Mbaabu',
                'contact_email' => 'info@jumia.ug',
                'contact_phone' => '+256200333000',
                'address1' => 'Jumia House, Plot 6, Nakasero Road, Kampala',
                'company_size' => '200-500',
                'industry_id' => 4, // E-commerce/Retail
                'is_active' => true,
                'is_verified' => true,
            ],
            [
                'name' => 'Kampala Serena Hotel',
                'slug' => Str::slug('Kampala Serena Hotel'),
                'logo' => 'companies/logos/serena-hotel.png',
                'description' => 'Kampala Serena Hotel is a five-star luxury hotel, offering world-class accommodation, dining, and conference facilities in the heart of Kampala.',
                'website' => 'https://www.serenahotels.com/kampala',
                'contact_email' => 'kampala@serena.co.ug',
                'contact_phone' => '+256312309000',
                'address1' => 'Kiira Road, Kampala',
                'company_size' => '200-500',
                'industry_id' => 5, // Hospitality/Tourism
                'is_active' => true,
                'is_verified' => true,
            ],
            [
                'name' => 'Sheraton Kampala Hotel',
                'slug' => Str::slug('Sheraton Kampala Hotel'),
                'logo' => 'companies/logos/sheraton-kampala.png',
                'description' => 'Sheraton Kampala Hotel is a premier five-star hotel, known for its exceptional service, luxury accommodations, and prime location in Kampala.',
                'website' => 'https://www.marriott.com',
                'contact_email' => 'info@sheratonkampala.com',
                'contact_phone' => '+256414420000',
                'address1' => 'Ternan Avenue, Kampala',
                'company_size' => '200-500',
                'industry_id' => 5, // Hospitality/Tourism
                'is_active' => true,
                'is_verified' => true,
            ],
            [
                'name' => 'Entebbe International Airport',
                'slug' => Str::slug('Entebbe International Airport'),
                'logo' => 'companies/logos/entebbe-airport.png',
                'description' => 'Entebbe International Airport is the main international airport of Uganda, serving as a gateway for travelers and cargo to and from the country.',
                'website' => 'https://www.caa.go.ug',
                'contact_name' => 'Fred Bamwesigye',
                'contact_email' => 'info@caa.go.ug',
                'contact_phone' => '+256414320000',
                'address1' => 'Entebbe International Airport, Entebbe',
                'company_size' => '500-1000',
                'industry_id' => 6, // Aviation/Transportation
                'is_active' => true,
                'is_verified' => true,
            ],
            [
                'name' => 'Uganda Revenue Authority',
                'slug' => Str::slug('Uganda Revenue Authority'),
                'logo' => 'companies/logos/ura.png',
                'description' => 'Uganda Revenue Authority is the government agency responsible for tax administration and customs services in Uganda.',
                'website' => 'https://www.ura.go.ug',
                'contact_name' => 'John Musinguzi',
                'contact_email' => 'info@ura.go.ug',
                'contact_phone' => '+256417442000',
                'address1' => 'URA Tower, Plot M193/M194, Nakawa, Kampala',
                'company_size' => '1000+',
                'industry_id' => 7, // Government/Public Sector
                'is_active' => true,
                'is_verified' => true,
            ],
            [
                'name' => 'National Social Security Fund (NSSF)',
                'slug' => Str::slug('NSSF Uganda'),
                'logo' => 'companies/logos/nssf.png',
                'description' => 'NSSF is Uganda\'s leading retirement savings scheme, providing social security services to employees across the country.',
                'website' => 'https://www.nssfug.org',
                'contact_name' => 'Patrick Ayota',
                'contact_email' => 'info@nssfug.org',
                'contact_phone' => '+256417100400',
                'address1' => 'Workers House, 1 Pilkington Road, Kampala',
                'company_size' => '500-1000',
                'industry_id' => 7, // Government/Public Sector
                'is_active' => true,
                'is_verified' => true,
            ],
            [
                'name' => 'Quality Chemical Industries Limited',
                'slug' => Str::slug('Quality Chemical Industries Limited'),
                'logo' => 'companies/logos/qcil.png',
                'description' => 'Quality Chemical Industries Limited is a leading pharmaceutical manufacturer in Uganda, known for producing antimalarial drugs and other medicines.',
                'website' => 'https://www.qcil.co.ug',
                'contact_name' => 'Emmanuel Katongole',
                'contact_email' => 'info@qcil.co.ug',
                'contact_phone' => '+256312350300',
                'address1' => 'Luzira Industrial Park, Kampala',
                'company_size' => '200-500',
                'industry_id' => 8, // Pharmaceutical/Healthcare
                'is_active' => true,
                'is_verified' => true,
            ],
            [
                'name' => 'Kampala Pharmaceutical Industries',
                'slug' => Str::slug('Kampala Pharmaceutical Industries'),
                'logo' => 'companies/logos/kpi.png',
                'description' => 'Kampala Pharmaceutical Industries is a major pharmaceutical company in Uganda, manufacturing and distributing essential medicines across East Africa.',
                'website' => 'https://www.kpilabs.com',
                'contact_email' => 'info@kpilabs.com',
                'contact_phone' => '+256414220035',
                'address1' => 'Plot 13-15, 7th Street Industrial Area, Kampala',
                'company_size' => '200-500',
                'industry_id' => 8, // Pharmaceutical/Healthcare
                'is_active' => true,
                'is_verified' => true,
            ],
            [
                'name' => 'Case Hospital',
                'slug' => Str::slug('Case Hospital'),
                'logo' => 'companies/logos/case-hospital.png',
                'description' => 'Case Hospital is a premier private healthcare facility in Kampala, offering specialized medical services and advanced diagnostic capabilities.',
                'website' => 'https://www.casehospital.ug',
                'contact_email' => 'info@casehospital.ug',
                'contact_phone' => '+256414347500',
                'address1' => 'Plot 21 Akii Bua Road, Kampala',
                'company_size' => '100-200',
                'industry_id' => 9, // Healthcare/Medical Services
                'is_active' => true,
                'is_verified' => true,
            ],
            [
                'name' => 'International Hospital Kampala',
                'slug' => Str::slug('International Hospital Kampala'),
                'logo' => 'companies/logos/ihk.png',
                'description' => 'International Hospital Kampala is one of Uganda\'s leading private hospitals, providing comprehensive healthcare services with state-of-the-art facilities.',
                'website' => 'https://www.ihk.co.ug',
                'contact_email' => 'info@ihk.co.ug',
                'contact_phone' => '+256417711000',
                'address1' => 'Plot 46-48, Jinja Road, Kampala',
                'company_size' => '200-500',
                'industry_id' => 9, // Healthcare/Medical Services
                'is_active' => true,
                'is_verified' => true,
            ],
            [
                'name' => 'Roofings Limited',
                'slug' => Str::slug('Roofings Limited'),
                'logo' => 'companies/logos/roofings.png',
                'description' => 'Roofings Limited is the largest manufacturer of steel building products in East Africa, supplying construction materials across the region.',
                'website' => 'https://www.roofingsgroup.com',
                'contact_email' => 'info@roofingsgroup.com',
                'contact_phone' => '+256414310040',
                'address1' => 'Plot 6-10, 7th Street Industrial Area, Kampala',
                'company_size' => '500-1000',
                'industry_id' => 10, // Construction/Manufacturing
                'is_active' => true,
                'is_verified' => true,
            ],
            [
                'name' => 'Hima Cement Limited',
                'slug' => Str::slug('Hima Cement Limited'),
                'logo' => 'companies/logos/hima-cement.png',
                'description' => 'Hima Cement Limited is a leading cement manufacturer in Uganda, producing high-quality cement for construction projects across the country.',
                'website' => 'https://www.himacement.com',
                'contact_email' => 'info@himacement.com',
                'contact_phone' => '+256312350800',
                'address1' => 'Plot 838, Block 216, Kasese Road, Kampala',
                'company_size' => '500-1000',
                'industry_id' => 10, // Construction/Manufacturing
                'is_active' => true,
                'is_verified' => true,
            ],
            [
                'name' => 'Mukwano Industries',
                'slug' => Str::slug('Mukwano Industries'),
                'logo' => 'companies/logos/mukwano.png',
                'description' => 'Mukwano Industries is one of Uganda\'s largest conglomerates, manufacturing consumer goods including soaps, detergents, cooking oils, and beverages.',
                'website' => 'https://www.mukwano.com',
                'contact_name' => 'Tony Gali',
                'contact_email' => 'info@mukwano.com',
                'contact_phone' => '+256414340800',
                'address1' => 'Mukwano House, Plot 1-5, 7th Street Industrial Area, Kampala',
                'company_size' => '1000+',
                'industry_id' => 3, // Manufacturing/FMCG
                'is_active' => true,
                'is_verified' => true,
            ],
            [
                'name' => 'Uganda Telecom Limited',
                'slug' => Str::slug('Uganda Telecom Limited'),
                'logo' => 'companies/logos/uganda-telecom.png',
                'description' => 'Uganda Telecom is one of the oldest telecommunications companies in Uganda, offering fixed and mobile telephony, internet, and data services.',
                'website' => 'https://www.utl.co.ug',
                'contact_email' => 'info@utl.co.ug',
                'contact_phone' => '+256800222333',
                'address1' => 'UTL Towers, Plot 6/8 Hannington Road, Kampala',
                'company_size' => '500-1000',
                'industry_id' => 1, // Telecommunications/Technology
                'is_active' => true,
                'is_verified' => true,
            ],
            [
                'name' => 'dfcu Bank',
                'slug' => Str::slug('dfcu Bank'),
                'logo' => 'companies/logos/dfcu.png',
                'description' => 'dfcu Bank is a leading commercial bank in Uganda, providing corporate, retail, and investment banking services to individuals and businesses.',
                'website' => 'https://www.dfcugroup.com',
                'contact_name' => 'Mathias Katamba',
                'contact_email' => 'info@dfcugroup.com',
                'contact_phone' => '+256417301000',
                'address1' => 'dfcu Towers, Plot 26 Kyadondo Road, Kampala',
                'company_size' => '500-1000',
                'industry_id' => 2, // Banking/Finance
                'is_active' => true,
                'is_verified' => true,
            ],
            [
                'name' => 'Pride Microfinance Limited',
                'slug' => Str::slug('Pride Microfinance Limited'),
                'logo' => 'companies/logos/pride.png',
                'description' => 'Pride Microfinance is the largest microfinance institution in Uganda, providing financial services to micro, small, and medium enterprises.',
                'website' => 'https://www.pridemicrofinance.co.ug',
                'contact_email' => 'info@pridemicrofinance.co.ug',
                'contact_phone' => '+256800299299',
                'address1' => 'Pride House, Plot 1, 7th Street Industrial Area, Kampala',
                'company_size' => '500-1000',
                'industry_id' => 2, // Banking/Finance
                'is_active' => true,
                'is_verified' => true,
            ],
            [
                'name' => 'PostBank Uganda',
                'slug' => Str::slug('PostBank Uganda'),
                'logo' => 'companies/logos/postbank.png',
                'description' => 'PostBank Uganda is a government-owned financial institution providing savings, loans, and money transfer services to Ugandans, with a focus on financial inclusion.',
                'website' => 'https://www.postbank.co.ug',
                'contact_name' => 'Julius Kakeeto',
                'contact_email' => 'info@postbank.co.ug',
                'contact_phone' => '+256417116200',
                'address1' => 'PostBank House, Plot 4-6 Nkrumah Road, Kampala',
                'company_size' => '500-1000',
                'industry_id' => 2, // Banking/Finance
                'is_active' => true,
                'is_verified' => true,
            ],
            [
                'name' => 'Bank of Baroda Uganda',
                'slug' => Str::slug('Bank of Baroda Uganda'),
                'logo' => 'companies/logos/baroda.png',
                'description' => 'Bank of Baroda Uganda is a subsidiary of India\'s Bank of Baroda, offering comprehensive banking services to individuals and corporations in Uganda.',
                'website' => 'https://www.bankofbaroda.ug',
                'contact_name' => 'Sanjay Rastogi',
                'contact_email' => 'info@bankofbaroda.ug',
                'contact_phone' => '+256414230595',
                'address1' => 'Bank of Baroda Building, 18 Kampala Road, Kampala',
                'company_size' => '200-500',
                'industry_id' => 2, // Banking/Finance
                'is_active' => true,
                'is_verified' => true,
            ],
            [
                'name' => 'Housing Finance Bank',
                'slug' => Str::slug('Housing Finance Bank'),
                'logo' => 'companies/logos/housing-finance.png',
                'description' => 'Housing Finance Bank is Uganda\'s leading mortgage lender, providing home loans, savings accounts, and other financial services.',
                'website' => 'https://www.housingfinance.co.ug',
                'contact_name' => 'Michael Mugabi',
                'contact_email' => 'info@housingfinance.co.ug',
                'contact_phone' => '+256417114700',
                'address1' => 'Housing Finance Bank House, Plot 4 Wampewo Avenue, Kololo, Kampala',
                'company_size' => '200-500',
                'industry_id' => 2, // Banking/Finance
                'is_active' => true,
                'is_verified' => true,
            ],
            [
                'name' => 'Cipla Quality Chemical Industries',
                'slug' => Str::slug('Cipla Quality Chemical Industries'),
                'logo' => 'companies/logos/cipla.png',
                'description' => 'Cipla Quality Chemical Industries is a leading pharmaceutical manufacturer in Uganda, producing antiretroviral drugs, antimalarials, and other essential medicines.',
                'website' => 'https://www.ciplaqci.com',
                'contact_name' => 'Emmanuel Katongole',
                'contact_email' => 'info@ciplaqci.com',
                'contact_phone' => '+256312350300',
                'address1' => 'Luzira Industrial Park, Kampala',
                'company_size' => '500-1000',
                'industry_id' => 8, // Pharmaceutical/Healthcare
                'is_active' => true,
                'is_verified' => true,
            ],
            [
                'name' => 'Roko Construction Limited',
                'slug' => Str::slug('Roko Construction Limited'),
                'logo' => 'companies/logos/roko.png',
                'description' => 'Roko Construction is one of Uganda\'s premier construction companies, known for developing high-quality commercial and residential properties across East Africa.',
                'website' => 'https://wwwrokoconstruction.com',
                'contact_name' => 'Robert Kabushenga',
                'contact_email' => 'info@rokoconstruction.com',
                'contact_phone' => '+256414344800',
                'address1' => 'Roko House, Plot 23 Acacia Avenue, Kololo, Kampala',
                'company_size' => '500-1000',
                'industry_id' => 10, // Construction/Manufacturing
                'is_active' => true,
                'is_verified' => true,
            ],
            [
                'name' => 'Excel Construction Limited',
                'slug' => Str::slug('Excel Construction Limited'),
                'logo' => 'companies/logos/excel.png',
                'description' => 'Excel Construction is a leading Ugandan construction company specializing in civil engineering works, road construction, and building projects.',
                'website' => 'https://www.excelconstruction.co.ug',
                'contact_name' => 'James Muwonge',
                'contact_email' => 'info@excelconstruction.co.ug',
                'contact_phone' => '+256414250000',
                'address1' => 'Excel Towers, Plot 6, Kampala Road, Kampala',
                'company_size' => '200-500',
                'industry_id' => 10, // Construction/Manufacturing
                'is_active' => true,
                'is_verified' => true,
            ],
            [
                'name' => 'Tullow Oil Uganda',
                'slug' => Str::slug('Tullow Oil Uganda'),
                'logo' => 'companies/logos/tullow.png',
                'description' => 'Tullow Oil Uganda is a leading oil exploration and production company, operating in the Lake Albert Rift Basin in Uganda.',
                'website' => 'https://www.tullowoil.com',
                'contact_name' => 'Nicole Binyereko',
                'contact_email' => 'info@tullowoil.com',
                'contact_phone' => '+256312350000',
                'address1' => 'Tullow Oil Offices, Plot 15, Acacia Avenue, Kololo, Kampala',
                'company_size' => '200-500',
                'industry_id' => 87, // Oil and Gas
                'is_active' => true,
                'is_verified' => true,
            ],
            [
                'name' => 'TotalEnergies Uganda',
                'slug' => Str::slug('TotalEnergies Uganda'),
                'logo' => 'companies/logos/total.png',
                'description' => 'TotalEnergies Uganda is a major player in the oil and gas sector, operating a network of service stations and involved in the Tilenga oil project.',
                'website' => 'https://www.totalenergies.ug',
                'contact_name' => 'Philippe Groueix',
                'contact_email' => 'info@totalenergies.ug',
                'contact_phone' => '+256414344000',
                'address1' => 'Total House, Plot 33, Kampala Road, Kampala',
                'company_size' => '200-500',
                'industry_id' => 87, // Oil and Gas
                'is_active' => true,
                'is_verified' => true,
            ],
            [
                'name' => 'Vivo Energy Uganda (Shell)',
                'slug' => Str::slug('Vivo Energy Uganda'),
                'logo' => 'companies/logos/vivo-shell.png',
                'description' => 'Vivo Energy Uganda operates the Shell brand in Uganda, distributing and retailing fuels, lubricants, and providing energy solutions.',
                'website' => 'https://www.vivoenergy.ug',
                'contact_name' => 'Kingsley Ighodalo',
                'contact_email' => 'info@vivoenergy.ug',
                'contact_phone' => '+256414343000',
                'address1' => 'Shell House, Plot 6, Lumumba Avenue, Kampala',
                'company_size' => '200-500',
                'industry_id' => 87, // Oil and Gas
                'is_active' => true,
                'is_verified' => true,
            ],
            [
                'name' => 'Uganda Wildlife Authority',
                'slug' => Str::slug('Uganda Wildlife Authority'),
                'logo' => 'companies/logos/uganda-wildlife.png',
                'description' => 'Uganda Wildlife Authority is the government agency responsible for managing Uganda\'s national parks, wildlife reserves, and conservation areas.',
                'website' => 'https://www.ugandawildlife.org',
                'contact_name' => 'Sam Mwandha',
                'contact_email' => 'info@ugandawildlife.org',
                'contact_phone' => '+256414355000',
                'address1' => 'UWA Headquarters, Plot 7, Kira Road, Kamwokya, Kampala',
                'company_size' => '500-1000',
                'industry_id' => 124, // Tourism
                'is_active' => true,
                'is_verified' => true,
            ],
            [
                'name' => 'Uganda Tourism Board',
                'slug' => Str::slug('Uganda Tourism Board'),
                'logo' => 'companies/logos/uganda-tourism.png',
                'description' => 'Uganda Tourism Board is the official government agency responsible for promoting Uganda as a premier tourist destination.',
                'website' => 'https://www.visituganda.com',
                'contact_name' => 'Lilly Ajarova',
                'contact_email' => 'info@ugandatourismboard.go.ug',
                'contact_phone' => '+256414342196',
                'address1' => 'UTB Headquarters, Plot 42, Windsor Crescent, Kololo, Kampala',
                'company_size' => '100-200',
                'industry_id' => 124, // Tourism
                'is_active' => true,
                'is_verified' => true,
            ],
            [
                'name' => 'Hotel Africana',
                'slug' => Str::slug('Hotel Africana'),
                'logo' => 'companies/logos/hotel-africana.png',
                'description' => 'Hotel Africana is one of Kampala\'s premier hotels, offering accommodation, conference facilities, and dining in a serene environment.',
                'website' => 'https://www.hotelafricana.com',
                'contact_name' => 'Rajiv Ruparelia',
                'contact_email' => 'info@hotelafricana.com',
                'contact_phone' => '+256414777500',
                'address1' => 'Plot 2-4, Wampewo Avenue, Kololo, Kampala',
                'company_size' => '200-500',
                'industry_id' => 53, // Hospitality
                'is_active' => true,
                'is_verified' => true,
            ],
            [
                'name' => 'Imperial Royale Hotel',
                'slug' => Str::slug('Imperial Royale Hotel'),
                'logo' => 'companies/logos/imperial-royale.png',
                'description' => 'Imperial Royale Hotel is a luxury hotel in the heart of Kampala, known for its world-class service, accommodation, and conference facilities.',
                'website' => 'https://www.imperialroyalehotel.com',
                'contact_name' => 'Sudhir Ruparelia',
                'contact_email' => 'info@imperialroyalehotel.com',
                'contact_phone' => '+256312223000',
                'address1' => 'Plot 2-4, Lumumba Avenue, Kampala',
                'company_size' => '200-500',
                'industry_id' => 53, // Hospitality
                'is_active' => true,
                'is_verified' => true,
            ],
            [
                'name' => 'Uganda Clays Limited',
                'slug' => Str::slug('Uganda Clays Limited'),
                'logo' => 'companies/logos/uganda-clays.png',
                'description' => 'Uganda Clays Limited is the leading manufacturer of clay building products in Uganda, producing high-quality bricks, tiles, and pavers.',
                'website' => 'https://www.ugandaclays.co.ug',
                'contact_name' => 'Raymond Mbiine',
                'contact_email' => 'info@ugandaclays.co.ug',
                'contact_phone' => '+256414230014',
                'address1' => 'Plot 114, Entebbe Road, Kampala',
                'company_size' => '200-500',
                'industry_id' => 10, // Construction/Manufacturing
                'is_active' => true,
                'is_verified' => true,
            ],
            [
                'name' => 'Britania Allied Industries',
                'slug' => Str::slug('Britania Allied Industries'),
                'logo' => 'companies/logos/britania.png',
                'description' => 'Britania Allied Industries is a leading food and beverage company in Uganda, manufacturing biscuits, confectioneries, and other food products.',
                'website' => 'https://www.britania.co.ug',
                'contact_name' => 'Sanjay Tanna',
                'contact_email' => 'info@britania.co.ug',
                'contact_phone' => '+256414200040',
                'address1' => 'Britania House, Plot 7, Jinja Road, Kampala',
                'company_size' => '200-500',
                'industry_id' => 42, // Food Production
                'is_active' => true,
                'is_verified' => true,
            ],

            [
                'name' => 'National Water and Sewerage Corporation',
                'slug' => Str::slug('National Water and Sewerage Corporation'),
                'logo' => 'companies/logos/nwsc.png',
                'description' => 'National Water and Sewerage Corporation is the government utility responsible for water supply and sewerage services in Uganda\'s urban areas.',
                'website' => 'https://www.nwsc.co.ug',
                'contact_name' => 'Johnson Amayo',
                'contact_email' => 'info@nwsc.co.ug',
                'contact_phone' => '+256414313400',
                'address1' => 'NWSC Headquarters, Plot 3, Nakasero Road, Kampala',
                'company_size' => '1000+',
                'industry_id' => 11, // Energy/Utilities
                'is_active' => true,
                'is_verified' => true,
            ],
        ];

        foreach ($companies as $companyData) {
            Company::create($companyData);
        }

        $this->command->info('====================================');
        $this->command->info('COMPANY SEEDER COMPLETED SUCCESSFULLY!');
        $this->command->info('====================================');
        $this->command->info('Total companies created: ' . count($companies));
        $this->command->info('====================================');
    }
}