<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use App\Models\Job\Industry;
use Illuminate\Support\Str;

class IndustrySeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $industries = [
            [
                'name' => 'Accounting',
                'slug' => Str::slug('Accounting'),
                'description' => 'Financial record keeping, auditing, tax preparation, and accounting services.',
                'meta_title' => 'Accounting Jobs',
                'meta_description' => 'Find accounting and finance jobs.',
                'icon' => 'industries/accounting.png',
                'is_active' => true,
                'sort_order' => 1,
            ],
            [
                'name' => 'Aerospace',
                'slug' => Str::slug('Aerospace'),
                'description' => 'Aircraft manufacturing, space exploration, satellites, and aviation technology.',
                'meta_title' => 'Aerospace Jobs',
                'meta_description' => 'Find aerospace and aviation jobs.',
                'icon' => 'industries/aerospace.png',
                'is_active' => true,
                'sort_order' => 2,
            ],
            [
                'name' => 'Agriculture',
                'slug' => Str::slug('Agriculture'),
                'description' => 'Farming, crop production, livestock, agribusiness, and agricultural technology.',
                'meta_title' => 'Agriculture Jobs',
                'meta_description' => 'Find agriculture and farming jobs.',
                'icon' => 'industries/agriculture.png',
                'is_active' => true,
                'sort_order' => 3,
            ],
            [
                'name' => 'Airlines',
                'slug' => Str::slug('Airlines'),
                'description' => 'Commercial aviation, passenger and cargo airlines, and flight operations.',
                'meta_title' => 'Airlines Jobs',
                'meta_description' => 'Find airline and aviation jobs.',
                'icon' => 'industries/airlines.png',
                'is_active' => true,
                'sort_order' => 4,
            ],
            [
                'name' => 'Apparel',
                'slug' => Str::slug('Apparel'),
                'description' => 'Clothing manufacturing, fashion design, textiles, and garment retail.',
                'meta_title' => 'Apparel Jobs',
                'meta_description' => 'Find apparel and fashion jobs.',
                'icon' => 'industries/apparel.png',
                'is_active' => true,
                'sort_order' => 5,
            ],
            [
                'name' => 'Architecture',
                'slug' => Str::slug('Architecture'),
                'description' => 'Building design, urban planning, landscape architecture, and construction documentation.',
                'meta_title' => 'Architecture Jobs',
                'meta_description' => 'Find architecture and design jobs.',
                'icon' => 'industries/architecture.png',
                'is_active' => true,
                'sort_order' => 6,
            ],
            [
                'name' => 'Arts',
                'slug' => Str::slug('Arts'),
                'description' => 'Visual arts, performing arts, galleries, museums, and creative expression.',
                'meta_title' => 'Arts Jobs',
                'meta_description' => 'Find arts and creative jobs.',
                'icon' => 'industries/arts.png',
                'is_active' => true,
                'sort_order' => 7,
            ],
            [
                'name' => 'Automotive',
                'slug' => Str::slug('Automotive'),
                'description' => 'Vehicle manufacturing, sales, repair, and automotive parts and services.',
                'meta_title' => 'Automotive Jobs',
                'meta_description' => 'Find automotive and vehicle jobs.',
                'icon' => 'industries/automotive.png',
                'is_active' => true,
                'sort_order' => 8,
            ],
            [
                'name' => 'Banking',
                'slug' => Str::slug('Banking'),
                'description' => 'Commercial banking, investment banking, retail banking, and financial services.',
                'meta_title' => 'Banking Jobs',
                'meta_description' => 'Find banking and finance jobs.',
                'icon' => 'industries/banking.png',
                'is_active' => true,
                'sort_order' => 9,
            ],
            [
                'name' => 'Biotechnology',
                'slug' => Str::slug('Biotechnology'),
                'description' => 'Biological research, genetic engineering, drug development, and medical innovations.',
                'meta_title' => 'Biotechnology Jobs',
                'meta_description' => 'Find biotech and research jobs.',
                'icon' => 'industries/biotechnology.png',
                'is_active' => true,
                'sort_order' => 10,
            ],
            [
                'name' => 'Broadcasting',
                'slug' => Str::slug('Broadcasting'),
                'description' => 'Television, radio, streaming media, and content distribution.',
                'meta_title' => 'Broadcasting Jobs',
                'meta_description' => 'Find broadcasting and media jobs.',
                'icon' => 'industries/broadcasting.png',
                'is_active' => true,
                'sort_order' => 11,
            ],
            [
                'name' => 'Business Services',
                'slug' => Str::slug('Business Services'),
                'description' => 'Consulting, outsourcing, business process management, and professional services.',
                'meta_title' => 'Business Services Jobs',
                'meta_description' => 'Find business services and consulting jobs.',
                'icon' => 'industries/business-services.png',
                'is_active' => true,
                'sort_order' => 12,
            ],
            [
                'name' => 'Chemical',
                'slug' => Str::slug('Chemical'),
                'description' => 'Chemical manufacturing, industrial chemicals, specialty chemicals, and materials.',
                'meta_title' => 'Chemical Jobs',
                'meta_description' => 'Find chemical industry jobs.',
                'icon' => 'industries/chemical.png',
                'is_active' => true,
                'sort_order' => 13,
            ],
            [
                'name' => 'Civil Engineering',
                'slug' => Str::slug('Civil Engineering'),
                'description' => 'Infrastructure development, construction engineering, and public works.',
                'meta_title' => 'Civil Engineering Jobs',
                'meta_description' => 'Find civil engineering and infrastructure jobs.',
                'icon' => 'industries/civil-engineering.png',
                'is_active' => true,
                'sort_order' => 14,
            ],
            [
                'name' => 'Commercial Real Estate',
                'slug' => Str::slug('Commercial Real Estate'),
                'description' => 'Office buildings, retail spaces, industrial properties, and commercial property management.',
                'meta_title' => 'Commercial Real Estate Jobs',
                'meta_description' => 'Find commercial real estate jobs.',
                'icon' => 'industries/commercial-real-estate.png',
                'is_active' => true,
                'sort_order' => 15,
            ],
            [
                'name' => 'Communications',
                'slug' => Str::slug('Communications'),
                'description' => 'Public relations, corporate communications, and media relations.',
                'meta_title' => 'Communications Jobs',
                'meta_description' => 'Find communications and PR jobs.',
                'icon' => 'industries/communications.png',
                'is_active' => true,
                'sort_order' => 16,
            ],
            [
                'name' => 'Computer Hardware',
                'slug' => Str::slug('Computer Hardware'),
                'description' => 'Computer manufacturing, hardware design, and electronic components.',
                'meta_title' => 'Computer Hardware Jobs',
                'meta_description' => 'Find computer hardware and electronics jobs.',
                'icon' => 'industries/computer-hardware.png',
                'is_active' => true,
                'sort_order' => 17,
            ],
            [
                'name' => 'Computer Networking',
                'slug' => Str::slug('Computer Networking'),
                'description' => 'Network infrastructure, data communications, and IT networking services.',
                'meta_title' => 'Computer Networking Jobs',
                'meta_description' => 'Find networking and IT infrastructure jobs.',
                'icon' => 'industries/computer-networking.png',
                'is_active' => true,
                'sort_order' => 18,
            ],
            [
                'name' => 'Computer Software',
                'slug' => Str::slug('Computer Software'),
                'description' => 'Software development, applications, and digital solutions.',
                'meta_title' => 'Software Jobs',
                'meta_description' => 'Find software development and engineering jobs.',
                'icon' => 'industries/computer-software.png',
                'is_active' => true,
                'sort_order' => 19,
            ],
            [
                'name' => 'Construction',
                'slug' => Str::slug('Construction'),
                'description' => 'Building construction, project management, and construction services.',
                'meta_title' => 'Construction Jobs',
                'meta_description' => 'Find construction and building jobs.',
                'icon' => 'industries/construction.png',
                'is_active' => true,
                'sort_order' => 20,
            ],
            [
                'name' => 'Consulting',
                'slug' => Str::slug('Consulting'),
                'description' => 'Management consulting, strategy, and business advisory services.',
                'meta_title' => 'Consulting Jobs',
                'meta_description' => 'Find consulting and strategy jobs.',
                'icon' => 'industries/consulting.png',
                'is_active' => true,
                'sort_order' => 21,
            ],
            [
                'name' => 'Consumer Electronics',
                'slug' => Str::slug('Consumer Electronics'),
                'description' => 'Electronic devices, gadgets, and consumer technology products.',
                'meta_title' => 'Consumer Electronics Jobs',
                'meta_description' => 'Find consumer electronics and tech jobs.',
                'icon' => 'industries/consumer-electronics.png',
                'is_active' => true,
                'sort_order' => 22,
            ],
            [
                'name' => 'Consumer Goods',
                'slug' => Str::slug('Consumer Goods'),
                'description' => 'Everyday consumer products, household goods, and personal care items.',
                'meta_title' => 'Consumer Goods Jobs',
                'meta_description' => 'Find consumer goods and FMCG jobs.',
                'icon' => 'industries/consumer-goods.png',
                'is_active' => true,
                'sort_order' => 23,
            ],
            [
                'name' => 'Cosmetics',
                'slug' => Str::slug('Cosmetics'),
                'description' => 'Beauty products, skincare, makeup, and personal care items.',
                'meta_title' => 'Cosmetics Jobs',
                'meta_description' => 'Find cosmetics and beauty jobs.',
                'icon' => 'industries/cosmetics.png',
                'is_active' => true,
                'sort_order' => 24,
            ],
            [
                'name' => 'Dairy',
                'slug' => Str::slug('Dairy'),
                'description' => 'Milk production, dairy products, and dairy farming.',
                'meta_title' => 'Dairy Jobs',
                'meta_description' => 'Find dairy and food production jobs.',
                'icon' => 'industries/dairy.png',
                'is_active' => true,
                'sort_order' => 25,
            ],
            [
                'name' => 'Defense',
                'slug' => Str::slug('Defense'),
                'description' => 'Military equipment, defense contracting, and national security.',
                'meta_title' => 'Defense Jobs',
                'meta_description' => 'Find defense and security jobs.',
                'icon' => 'industries/defense.png',
                'is_active' => true,
                'sort_order' => 26,
            ],
            [
                'name' => 'Design',
                'slug' => Str::slug('Design'),
                'description' => 'Graphic design, product design, UX/UI, and creative services.',
                'meta_title' => 'Design Jobs',
                'meta_description' => 'Find design and creative jobs.',
                'icon' => 'industries/design.png',
                'is_active' => true,
                'sort_order' => 27,
            ],
            [
                'name' => 'E-commerce',
                'slug' => Str::slug('E-commerce'),
                'description' => 'Online retail, digital marketplaces, and electronic commerce.',
                'meta_title' => 'E-commerce Jobs',
                'meta_description' => 'Find e-commerce and online retail jobs.',
                'icon' => 'industries/e-commerce.png',
                'is_active' => true,
                'sort_order' => 28,
            ],
            [
                'name' => 'Education',
                'slug' => Str::slug('Education'),
                'description' => 'Schools, universities, training, and educational services.',
                'meta_title' => 'Education Jobs',
                'meta_description' => 'Find education and teaching jobs.',
                'icon' => 'industries/education.png',
                'is_active' => true,
                'sort_order' => 29,
            ],
            [
                'name' => 'Electrical Engineering',
                'slug' => Str::slug('Electrical Engineering'),
                'description' => 'Electrical systems, power generation, and electronic engineering.',
                'meta_title' => 'Electrical Engineering Jobs',
                'meta_description' => 'Find electrical engineering jobs.',
                'icon' => 'industries/electrical-engineering.png',
                'is_active' => true,
                'sort_order' => 30,
            ],
            [
                'name' => 'Electronics',
                'slug' => Str::slug('Electronics'),
                'description' => 'Electronic components, circuit design, and electronic manufacturing.',
                'meta_title' => 'Electronics Jobs',
                'meta_description' => 'Find electronics and components jobs.',
                'icon' => 'industries/electronics.png',
                'is_active' => true,
                'sort_order' => 31,
            ],
            [
                'name' => 'Energy',
                'slug' => Str::slug('Energy'),
                'description' => 'Power generation, oil and gas, renewable energy, and utilities.',
                'meta_title' => 'Energy Jobs',
                'meta_description' => 'Find energy and utilities jobs.',
                'icon' => 'industries/energy.png',
                'is_active' => true,
                'sort_order' => 32,
            ],
            [
                'name' => 'Engineering',
                'slug' => Str::slug('Engineering'),
                'description' => 'General engineering, technical services, and engineering solutions.',
                'meta_title' => 'Engineering Jobs',
                'meta_description' => 'Find engineering and technical jobs.',
                'icon' => 'industries/engineering.png',
                'is_active' => true,
                'sort_order' => 33,
            ],
            [
                'name' => 'Entertainment',
                'slug' => Str::slug('Entertainment'),
                'description' => 'Movies, music, events, and entertainment production.',
                'meta_title' => 'Entertainment Jobs',
                'meta_description' => 'Find entertainment and media jobs.',
                'icon' => 'industries/entertainment.png',
                'is_active' => true,
                'sort_order' => 34,
            ],
            [
                'name' => 'Environmental Services',
                'slug' => Str::slug('Environmental Services'),
                'description' => 'Environmental consulting, waste management, and sustainability.',
                'meta_title' => 'Environmental Jobs',
                'meta_description' => 'Find environmental and sustainability jobs.',
                'icon' => 'industries/environmental-services.png',
                'is_active' => true,
                'sort_order' => 35,
            ],
            [
                'name' => 'Event Services',
                'slug' => Str::slug('Event Services'),
                'description' => 'Event planning, management, and coordination services.',
                'meta_title' => 'Event Jobs',
                'meta_description' => 'Find event planning and management jobs.',
                'icon' => 'industries/event-services.png',
                'is_active' => true,
                'sort_order' => 36,
            ],
            [
                'name' => 'Fashion',
                'slug' => Str::slug('Fashion'),
                'description' => 'Fashion design, clothing retail, and fashion industry.',
                'meta_title' => 'Fashion Jobs',
                'meta_description' => 'Find fashion and design jobs.',
                'icon' => 'industries/fashion.png',
                'is_active' => true,
                'sort_order' => 37,
            ],
            [
                'name' => 'Film',
                'slug' => Str::slug('Film'),
                'description' => 'Movie production, cinematography, and film industry.',
                'meta_title' => 'Film Jobs',
                'meta_description' => 'Find film and movie production jobs.',
                'icon' => 'industries/film.png',
                'is_active' => true,
                'sort_order' => 38,
            ],
            [
                'name' => 'Financial Services',
                'slug' => Str::slug('Financial Services'),
                'description' => 'Investment, wealth management, and financial advisory.',
                'meta_title' => 'Financial Services Jobs',
                'meta_description' => 'Find financial services and investment jobs.',
                'icon' => 'industries/financial-services.png',
                'is_active' => true,
                'sort_order' => 39,
            ],
            [
                'name' => 'Fine Art',
                'slug' => Str::slug('Fine Art'),
                'description' => 'Art galleries, fine art sales, and artistic services.',
                'meta_title' => 'Fine Art Jobs',
                'meta_description' => 'Find fine art and gallery jobs.',
                'icon' => 'industries/fine-art.png',
                'is_active' => true,
                'sort_order' => 40,
            ],
            [
                'name' => 'Fishery',
                'slug' => Str::slug('Fishery'),
                'description' => 'Fishing industry, aquaculture, and fish processing.',
                'meta_title' => 'Fishery Jobs',
                'meta_description' => 'Find fishery and aquaculture jobs.',
                'icon' => 'industries/fishery.png',
                'is_active' => true,
                'sort_order' => 41,
            ],
            [
                'name' => 'Food Production',
                'slug' => Str::slug('Food Production'),
                'description' => 'Food manufacturing, processing, and packaging.',
                'meta_title' => 'Food Production Jobs',
                'meta_description' => 'Find food production and processing jobs.',
                'icon' => 'industries/food-production.png',
                'is_active' => true,
                'sort_order' => 42,
            ],
            [
                'name' => 'Food Services',
                'slug' => Str::slug('Food Services'),
                'description' => 'Restaurants, catering, and food service establishments.',
                'meta_title' => 'Food Services Jobs',
                'meta_description' => 'Find restaurant and food service jobs.',
                'icon' => 'industries/food-services.png',
                'is_active' => true,
                'sort_order' => 43,
            ],
            [
                'name' => 'Forestry',
                'slug' => Str::slug('Forestry'),
                'description' => 'Forest management, logging, and timber production.',
                'meta_title' => 'Forestry Jobs',
                'meta_description' => 'Find forestry and timber jobs.',
                'icon' => 'industries/forestry.png',
                'is_active' => true,
                'sort_order' => 44,
            ],
            [
                'name' => 'Furniture',
                'slug' => Str::slug('Furniture'),
                'description' => 'Furniture manufacturing, retail, and design.',
                'meta_title' => 'Furniture Jobs',
                'meta_description' => 'Find furniture and design jobs.',
                'icon' => 'industries/furniture.png',
                'is_active' => true,
                'sort_order' => 45,
            ],
            [
                'name' => 'Gaming',
                'slug' => Str::slug('Gaming'),
                'description' => 'Video game development, gaming industry, and esports.',
                'meta_title' => 'Gaming Jobs',
                'meta_description' => 'Find gaming and esports jobs.',
                'icon' => 'industries/gaming.png',
                'is_active' => true,
                'sort_order' => 46,
            ],
            [
                'name' => 'Government',
                'slug' => Str::slug('Government'),
                'description' => 'Public sector, government agencies, and civil service.',
                'meta_title' => 'Government Jobs',
                'meta_description' => 'Find government and public sector jobs.',
                'icon' => 'industries/government.png',
                'is_active' => true,
                'sort_order' => 47,
            ],
            [
                'name' => 'Graphic Design',
                'slug' => Str::slug('Graphic Design'),
                'description' => 'Visual communication, branding, and design services.',
                'meta_title' => 'Graphic Design Jobs',
                'meta_description' => 'Find graphic design and visual arts jobs.',
                'icon' => 'industries/graphic-design.png',
                'is_active' => true,
                'sort_order' => 48,
            ],
            [
                'name' => 'Health and Human Services',
                'slug' => Str::slug('Health and Human Services'),
                'description' => 'Public health, social services, and community programs.',
                'meta_title' => 'Health and Human Services Jobs',
                'meta_description' => 'Find health and human services jobs.',
                'icon' => 'industries/health-services.png',
                'is_active' => true,
                'sort_order' => 49,
            ],
            [
                'name' => 'Healthcare',
                'slug' => Str::slug('Healthcare'),
                'description' => 'Medical services, hospitals, and healthcare facilities.',
                'meta_title' => 'Healthcare Jobs',
                'meta_description' => 'Find healthcare and medical jobs.',
                'icon' => 'industries/healthcare.png',
                'is_active' => true,
                'sort_order' => 50,
            ],
            [
                'name' => 'Higher Education',
                'slug' => Str::slug('Higher Education'),
                'description' => 'Universities, colleges, and tertiary education.',
                'meta_title' => 'Higher Education Jobs',
                'meta_description' => 'Find university and college jobs.',
                'icon' => 'industries/higher-education.png',
                'is_active' => true,
                'sort_order' => 51,
            ],
            [
                'name' => 'Horticulture',
                'slug' => Str::slug('Horticulture'),
                'description' => 'Gardening, landscaping, and plant cultivation.',
                'meta_title' => 'Horticulture Jobs',
                'meta_description' => 'Find horticulture and landscaping jobs.',
                'icon' => 'industries/horticulture.png',
                'is_active' => true,
                'sort_order' => 52,
            ],
            [
                'name' => 'Hospitality',
                'slug' => Str::slug('Hospitality'),
                'description' => 'Hotels, accommodation, and hospitality services.',
                'meta_title' => 'Hospitality Jobs',
                'meta_description' => 'Find hotel and hospitality jobs.',
                'icon' => 'industries/hospitality.png',
                'is_active' => true,
                'sort_order' => 53,
            ],
            [
                'name' => 'Human Resources',
                'slug' => Str::slug('Human Resources'),
                'description' => 'HR services, recruitment, and personnel management.',
                'meta_title' => 'Human Resources Jobs',
                'meta_description' => 'Find HR and recruitment jobs.',
                'icon' => 'industries/human-resources.png',
                'is_active' => true,
                'sort_order' => 54,
            ],
            [
                'name' => 'Information Technology',
                'slug' => Str::slug('Information Technology'),
                'description' => 'IT services, software, and technology solutions.',
                'meta_title' => 'IT Jobs',
                'meta_description' => 'Find information technology and software jobs.',
                'icon' => 'industries/information-technology.png',
                'is_active' => true,
                'sort_order' => 55,
            ],
            [
                'name' => 'Insurance',
                'slug' => Str::slug('Insurance'),
                'description' => 'Insurance services, underwriting, and claims processing.',
                'meta_title' => 'Insurance Jobs',
                'meta_description' => 'Find insurance and underwriting jobs.',
                'icon' => 'industries/insurance.png',
                'is_active' => true,
                'sort_order' => 56,
            ],
            [
                'name' => 'Interior Design',
                'slug' => Str::slug('Interior Design'),
                'description' => 'Interior decoration, space planning, and design services.',
                'meta_title' => 'Interior Design Jobs',
                'meta_description' => 'Find interior design and decoration jobs.',
                'icon' => 'industries/interior-design.png',
                'is_active' => true,
                'sort_order' => 57,
            ],
            [
                'name' => 'International Trade',
                'slug' => Str::slug('International Trade'),
                'description' => 'Global commerce, import/export, and trade services.',
                'meta_title' => 'International Trade Jobs',
                'meta_description' => 'Find international trade and commerce jobs.',
                'icon' => 'industries/international-trade.png',
                'is_active' => true,
                'sort_order' => 58,
            ],
            [
                'name' => 'Internet',
                'slug' => Str::slug('Internet'),
                'description' => 'Online services, web companies, and internet platforms.',
                'meta_title' => 'Internet Jobs',
                'meta_description' => 'Find internet and online services jobs.',
                'icon' => 'industries/internet.png',
                'is_active' => true,
                'sort_order' => 59,
            ],
            [
                'name' => 'Investment Banking',
                'slug' => Str::slug('Investment Banking'),
                'description' => 'Investment services, mergers and acquisitions, and capital markets.',
                'meta_title' => 'Investment Banking Jobs',
                'meta_description' => 'Find investment banking and finance jobs.',
                'icon' => 'industries/investment-banking.png',
                'is_active' => true,
                'sort_order' => 60,
            ],
            [
                'name' => 'Investment Management',
                'slug' => Str::slug('Investment Management'),
                'description' => 'Asset management, portfolio management, and investment advisory.',
                'meta_title' => 'Investment Management Jobs',
                'meta_description' => 'Find investment management and advisory jobs.',
                'icon' => 'industries/investment-management.png',
                'is_active' => true,
                'sort_order' => 61,
            ],
            [
                'name' => 'Journalism',
                'slug' => Str::slug('Journalism'),
                'description' => 'News reporting, writing, and media journalism.',
                'meta_title' => 'Journalism Jobs',
                'meta_description' => 'Find journalism and reporting jobs.',
                'icon' => 'industries/journalism.png',
                'is_active' => true,
                'sort_order' => 62,
            ],
            [
                'name' => 'Landscaping',
                'slug' => Str::slug('Landscaping'),
                'description' => 'Landscape design, gardening, and outdoor services.',
                'meta_title' => 'Landscaping Jobs',
                'meta_description' => 'Find landscaping and gardening jobs.',
                'icon' => 'industries/landscaping.png',
                'is_active' => true,
                'sort_order' => 63,
            ],
            [
                'name' => 'Law Enforcement',
                'slug' => Str::slug('Law Enforcement'),
                'description' => 'Police, security services, and law enforcement agencies.',
                'meta_title' => 'Law Enforcement Jobs',
                'meta_description' => 'Find law enforcement and security jobs.',
                'icon' => 'industries/law-enforcement.png',
                'is_active' => true,
                'sort_order' => 64,
            ],
            [
                'name' => 'Law Practice',
                'slug' => Str::slug('Law Practice'),
                'description' => 'Legal services, law firms, and legal advisory.',
                'meta_title' => 'Law Jobs',
                'meta_description' => 'Find legal and law practice jobs.',
                'icon' => 'industries/law-practice.png',
                'is_active' => true,
                'sort_order' => 65,
            ],
            [
                'name' => 'Legal Services',
                'slug' => Str::slug('Legal Services'),
                'description' => 'Legal support, paralegal services, and legal assistance.',
                'meta_title' => 'Legal Services Jobs',
                'meta_description' => 'Find legal services and support jobs.',
                'icon' => 'industries/legal-services.png',
                'is_active' => true,
                'sort_order' => 66,
            ],
            [
                'name' => 'Leisure',
                'slug' => Str::slug('Leisure'),
                'description' => 'Recreation, entertainment, and leisure activities.',
                'meta_title' => 'Leisure Jobs',
                'meta_description' => 'Find leisure and recreation jobs.',
                'icon' => 'industries/leisure.png',
                'is_active' => true,
                'sort_order' => 67,
            ],
            [
                'name' => 'Logistics',
                'slug' => Str::slug('Logistics'),
                'description' => 'Supply chain, transportation, and logistics services.',
                'meta_title' => 'Logistics Jobs',
                'meta_description' => 'Find logistics and supply chain jobs.',
                'icon' => 'industries/logistics.png',
                'is_active' => true,
                'sort_order' => 68,
            ],
            [
                'name' => 'Machinery',
                'slug' => Str::slug('Machinery'),
                'description' => 'Industrial equipment, machinery manufacturing, and maintenance.',
                'meta_title' => 'Machinery Jobs',
                'meta_description' => 'Find machinery and industrial equipment jobs.',
                'icon' => 'industries/machinery.png',
                'is_active' => true,
                'sort_order' => 69,
            ],
            [
                'name' => 'Management Consulting',
                'slug' => Str::slug('Management Consulting'),
                'description' => 'Business strategy, management advice, and consulting services.',
                'meta_title' => 'Management Consulting Jobs',
                'meta_description' => 'Find management consulting and strategy jobs.',
                'icon' => 'industries/management-consulting.png',
                'is_active' => true,
                'sort_order' => 70,
            ],
            [
                'name' => 'Manufacturing',
                'slug' => Str::slug('Manufacturing'),
                'description' => 'Production, industrial manufacturing, and fabrication.',
                'meta_title' => 'Manufacturing Jobs',
                'meta_description' => 'Find manufacturing and production jobs.',
                'icon' => 'industries/manufacturing.png',
                'is_active' => true,
                'sort_order' => 71,
            ],
            [
                'name' => 'Maritime',
                'slug' => Str::slug('Maritime'),
                'description' => 'Shipping, ports, and marine transportation.',
                'meta_title' => 'Maritime Jobs',
                'meta_description' => 'Find maritime and shipping jobs.',
                'icon' => 'industries/maritime.png',
                'is_active' => true,
                'sort_order' => 72,
            ],
            [
                'name' => 'Marketing',
                'slug' => Str::slug('Marketing'),
                'description' => 'Marketing services, advertising, and brand management.',
                'meta_title' => 'Marketing Jobs',
                'meta_description' => 'Find marketing and advertising jobs.',
                'icon' => 'industries/marketing.png',
                'is_active' => true,
                'sort_order' => 73,
            ],
            [
                'name' => 'Mechanical Engineering',
                'slug' => Str::slug('Mechanical Engineering'),
                'description' => 'Mechanical systems, design, and engineering services.',
                'meta_title' => 'Mechanical Engineering Jobs',
                'meta_description' => 'Find mechanical engineering jobs.',
                'icon' => 'industries/mechanical-engineering.png',
                'is_active' => true,
                'sort_order' => 74,
            ],
            [
                'name' => 'Media',
                'slug' => Str::slug('Media'),
                'description' => 'Media production, publishing, and content creation.',
                'meta_title' => 'Media Jobs',
                'meta_description' => 'Find media and publishing jobs.',
                'icon' => 'industries/media.png',
                'is_active' => true,
                'sort_order' => 75,
            ],
            [
                'name' => 'Medical Devices',
                'slug' => Str::slug('Medical Devices'),
                'description' => 'Medical equipment, devices, and healthcare technology.',
                'meta_title' => 'Medical Devices Jobs',
                'meta_description' => 'Find medical devices and equipment jobs.',
                'icon' => 'industries/medical-devices.png',
                'is_active' => true,
                'sort_order' => 76,
            ],
            [
                'name' => 'Medical Practice',
                'slug' => Str::slug('Medical Practice'),
                'description' => 'Medical clinics, doctor practices, and healthcare providers.',
                'meta_title' => 'Medical Practice Jobs',
                'meta_description' => 'Find medical practice and clinical jobs.',
                'icon' => 'industries/medical-practice.png',
                'is_active' => true,
                'sort_order' => 77,
            ],
            [
                'name' => 'Mental Health',
                'slug' => Str::slug('Mental Health'),
                'description' => 'Mental health services, counseling, and therapy.',
                'meta_title' => 'Mental Health Jobs',
                'meta_description' => 'Find mental health and counseling jobs.',
                'icon' => 'industries/mental-health.png',
                'is_active' => true,
                'sort_order' => 78,
            ],
            [
                'name' => 'Mining',
                'slug' => Str::slug('Mining'),
                'description' => 'Mineral extraction, mining operations, and resources.',
                'meta_title' => 'Mining Jobs',
                'meta_description' => 'Find mining and resources jobs.',
                'icon' => 'industries/mining.png',
                'is_active' => true,
                'sort_order' => 79,
            ],
            [
                'name' => 'Motion Pictures',
                'slug' => Str::slug('Motion Pictures'),
                'description' => 'Film production, movie industry, and cinematography.',
                'meta_title' => 'Motion Pictures Jobs',
                'meta_description' => 'Find film and motion picture jobs.',
                'icon' => 'industries/motion-pictures.png',
                'is_active' => true,
                'sort_order' => 80,
            ],
            [
                'name' => 'Museums',
                'slug' => Str::slug('Museums'),
                'description' => 'Museum operations, curation, and cultural heritage.',
                'meta_title' => 'Museums Jobs',
                'meta_description' => 'Find museum and curation jobs.',
                'icon' => 'industries/museums.png',
                'is_active' => true,
                'sort_order' => 81,
            ],
            [
                'name' => 'Music',
                'slug' => Str::slug('Music'),
                'description' => 'Music industry, production, and performance.',
                'meta_title' => 'Music Jobs',
                'meta_description' => 'Find music and performance jobs.',
                'icon' => 'industries/music.png',
                'is_active' => true,
                'sort_order' => 82,
            ],
            [
                'name' => 'Nanotechnology',
                'slug' => Str::slug('Nanotechnology'),
                'description' => 'Nano-scale science, engineering, and technology.',
                'meta_title' => 'Nanotechnology Jobs',
                'meta_description' => 'Find nanotechnology and research jobs.',
                'icon' => 'industries/nanotechnology.png',
                'is_active' => true,
                'sort_order' => 83,
            ],
            [
                'name' => 'Newspapers',
                'slug' => Str::slug('Newspapers'),
                'description' => 'News publishing, print media, and journalism.',
                'meta_title' => 'Newspapers Jobs',
                'meta_description' => 'Find newspaper and publishing jobs.',
                'icon' => 'industries/newspapers.png',
                'is_active' => true,
                'sort_order' => 84,
            ],
            [
                'name' => 'Nonprofit',
                'slug' => Str::slug('Nonprofit'),
                'description' => 'Nonprofit organizations, charities, and social services.',
                'meta_title' => 'Nonprofit Jobs',
                'meta_description' => 'Find nonprofit and charity jobs.',
                'icon' => 'industries/nonprofit.png',
                'is_active' => true,
                'sort_order' => 85,
            ],
            [
                'name' => 'Nuclear',
                'slug' => Str::slug('Nuclear'),
                'description' => 'Nuclear energy, power, and technology.',
                'meta_title' => 'Nuclear Jobs',
                'meta_description' => 'Find nuclear energy and technology jobs.',
                'icon' => 'industries/nuclear.png',
                'is_active' => true,
                'sort_order' => 86,
            ],
            [
                'name' => 'Oil and Gas',
                'slug' => Str::slug('Oil and Gas'),
                'description' => 'Petroleum exploration, production, and refining.',
                'meta_title' => 'Oil and Gas Jobs',
                'meta_description' => 'Find oil and gas industry jobs.',
                'icon' => 'industries/oil-gas.png',
                'is_active' => true,
                'sort_order' => 87,
            ],
            [
                'name' => 'Online Media',
                'slug' => Str::slug('Online Media'),
                'description' => 'Digital media, online publishing, and content platforms.',
                'meta_title' => 'Online Media Jobs',
                'meta_description' => 'Find online media and digital content jobs.',
                'icon' => 'industries/online-media.png',
                'is_active' => true,
                'sort_order' => 88,
            ],
            [
                'name' => 'Packaging',
                'slug' => Str::slug('Packaging'),
                'description' => 'Packaging manufacturing, design, and materials.',
                'meta_title' => 'Packaging Jobs',
                'meta_description' => 'Find packaging and container jobs.',
                'icon' => 'industries/packaging.png',
                'is_active' => true,
                'sort_order' => 89,
            ],
            [
                'name' => 'Paper',
                'slug' => Str::slug('Paper'),
                'description' => 'Paper manufacturing, products, and forest products.',
                'meta_title' => 'Paper Jobs',
                'meta_description' => 'Find paper and forest products jobs.',
                'icon' => 'industries/paper.png',
                'is_active' => true,
                'sort_order' => 90,
            ],
            [
                'name' => 'Performing Arts',
                'slug' => Str::slug('Performing Arts'),
                'description' => 'Theater, dance, and performing arts productions.',
                'meta_title' => 'Performing Arts Jobs',
                'meta_description' => 'Find performing arts and theater jobs.',
                'icon' => 'industries/performing-arts.png',
                'is_active' => true,
                'sort_order' => 91,
            ],
            [
                'name' => 'Pharmaceuticals',
                'slug' => Str::slug('Pharmaceuticals'),
                'description' => 'Drug manufacturing, research, and pharmaceutical products.',
                'meta_title' => 'Pharmaceutical Jobs',
                'meta_description' => 'Find pharmaceutical and drug manufacturing jobs.',
                'icon' => 'industries/pharmaceuticals.png',
                'is_active' => true,
                'sort_order' => 92,
            ],
            [
                'name' => 'Philanthropy',
                'slug' => Str::slug('Philanthropy'),
                'description' => 'Charitable giving, foundations, and grant-making.',
                'meta_title' => 'Philanthropy Jobs',
                'meta_description' => 'Find philanthropy and foundation jobs.',
                'icon' => 'industries/philanthropy.png',
                'is_active' => true,
                'sort_order' => 93,
            ],
            [
                'name' => 'Photography',
                'slug' => Str::slug('Photography'),
                'description' => 'Photography services, studios, and visual arts.',
                'meta_title' => 'Photography Jobs',
                'meta_description' => 'Find photography and visual arts jobs.',
                'icon' => 'industries/photography.png',
                'is_active' => true,
                'sort_order' => 94,
            ],
            [
                'name' => 'Plastics',
                'slug' => Str::slug('Plastics'),
                'description' => 'Plastic manufacturing, products, and materials.',
                'meta_title' => 'Plastics Jobs',
                'meta_description' => 'Find plastics and materials jobs.',
                'icon' => 'industries/plastics.png',
                'is_active' => true,
                'sort_order' => 95,
            ],
            [
                'name' => 'Political Organization',
                'slug' => Str::slug('Political Organization'),
                'description' => 'Political campaigns, parties, and organizations.',
                'meta_title' => 'Political Jobs',
                'meta_description' => 'Find political and campaign jobs.',
                'icon' => 'industries/political.png',
                'is_active' => true,
                'sort_order' => 96,
            ],
            [
                'name' => 'Printing',
                'slug' => Str::slug('Printing'),
                'description' => 'Print services, publishing, and graphic reproduction.',
                'meta_title' => 'Printing Jobs',
                'meta_description' => 'Find printing and publishing jobs.',
                'icon' => 'industries/printing.png',
                'is_active' => true,
                'sort_order' => 97,
            ],
            [
                'name' => 'Professional Services',
                'slug' => Str::slug('Professional Services'),
                'description' => 'Professional consulting, advisory, and business services.',
                'meta_title' => 'Professional Services Jobs',
                'meta_description' => 'Find professional services and consulting jobs.',
                'icon' => 'industries/professional-services.png',
                'is_active' => true,
                'sort_order' => 98,
            ],
            [
                'name' => 'Public Relations',
                'slug' => Str::slug('Public Relations'),
                'description' => 'PR services, communications, and media relations.',
                'meta_title' => 'Public Relations Jobs',
                'meta_description' => 'Find PR and communications jobs.',
                'icon' => 'industries/public-relations.png',
                'is_active' => true,
                'sort_order' => 99,
            ],
            [
                'name' => 'Public Safety',
                'slug' => Str::slug('Public Safety'),
                'description' => 'Emergency services, safety, and public protection.',
                'meta_title' => 'Public Safety Jobs',
                'meta_description' => 'Find public safety and emergency services jobs.',
                'icon' => 'industries/public-safety.png',
                'is_active' => true,
                'sort_order' => 100,
            ],
            [
                'name' => 'Publishing',
                'slug' => Str::slug('Publishing'),
                'description' => 'Book publishing, content creation, and editorial services.',
                'meta_title' => 'Publishing Jobs',
                'meta_description' => 'Find publishing and editorial jobs.',
                'icon' => 'industries/publishing.png',
                'is_active' => true,
                'sort_order' => 101,
            ],
            [
                'name' => 'Railroad',
                'slug' => Str::slug('Railroad'),
                'description' => 'Rail transport, freight, and railway services.',
                'meta_title' => 'Railroad Jobs',
                'meta_description' => 'Find railroad and railway jobs.',
                'icon' => 'industries/railroad.png',
                'is_active' => true,
                'sort_order' => 102,
            ],
            [
                'name' => 'Real Estate',
                'slug' => Str::slug('Real Estate'),
                'description' => 'Property sales, development, and real estate services.',
                'meta_title' => 'Real Estate Jobs',
                'meta_description' => 'Find real estate and property jobs.',
                'icon' => 'industries/real-estate.png',
                'is_active' => true,
                'sort_order' => 103,
            ],
            [
                'name' => 'Recreation',
                'slug' => Str::slug('Recreation'),
                'description' => 'Recreational activities, parks, and leisure services.',
                'meta_title' => 'Recreation Jobs',
                'meta_description' => 'Find recreation and leisure jobs.',
                'icon' => 'industries/recreation.png',
                'is_active' => true,
                'sort_order' => 104,
            ],
            [
                'name' => 'Recycling',
                'slug' => Str::slug('Recycling'),
                'description' => 'Waste recycling, materials recovery, and sustainability.',
                'meta_title' => 'Recycling Jobs',
                'meta_description' => 'Find recycling and waste management jobs.',
                'icon' => 'industries/recycling.png',
                'is_active' => true,
                'sort_order' => 105,
            ],
            [
                'name' => 'Renewables',
                'slug' => Str::slug('Renewables'),
                'description' => 'Renewable energy, solar, wind, and clean technology.',
                'meta_title' => 'Renewables Jobs',
                'meta_description' => 'Find renewable energy and clean tech jobs.',
                'icon' => 'industries/renewables.png',
                'is_active' => true,
                'sort_order' => 106,
            ],
            [
                'name' => 'Research',
                'slug' => Str::slug('Research'),
                'description' => 'Scientific research, development, and innovation.',
                'meta_title' => 'Research Jobs',
                'meta_description' => 'Find research and development jobs.',
                'icon' => 'industries/research.png',
                'is_active' => true,
                'sort_order' => 107,
            ],
            [
                'name' => 'Restaurants',
                'slug' => Str::slug('Restaurants'),
                'description' => 'Food service, dining, and restaurant operations.',
                'meta_title' => 'Restaurant Jobs',
                'meta_description' => 'Find restaurant and food service jobs.',
                'icon' => 'industries/restaurants.png',
                'is_active' => true,
                'sort_order' => 108,
            ],
            [
                'name' => 'Retail',
                'slug' => Str::slug('Retail'),
                'description' => 'Retail sales, stores, and consumer goods distribution.',
                'meta_title' => 'Retail Jobs',
                'meta_description' => 'Find retail and sales jobs.',
                'icon' => 'industries/retail.png',
                'is_active' => true,
                'sort_order' => 109,
            ],
            [
                'name' => 'Robotics',
                'slug' => Str::slug('Robotics'),
                'description' => 'Robotics engineering, automation, and intelligent systems.',
                'meta_title' => 'Robotics Jobs',
                'meta_description' => 'Find robotics and automation jobs.',
                'icon' => 'industries/robotics.png',
                'is_active' => true,
                'sort_order' => 110,
            ],
            [
                'name' => 'Safety',
                'slug' => Str::slug('Safety'),
                'description' => 'Workplace safety, compliance, and risk management.',
                'meta_title' => 'Safety Jobs',
                'meta_description' => 'Find safety and compliance jobs.',
                'icon' => 'industries/safety.png',
                'is_active' => true,
                'sort_order' => 111,
            ],
            [
                'name' => 'Sales',
                'slug' => Str::slug('Sales'),
                'description' => 'Sales, business development, and account management.',
                'meta_title' => 'Sales Jobs',
                'meta_description' => 'Find sales and business development jobs.',
                'icon' => 'industries/sales.png',
                'is_active' => true,
                'sort_order' => 112,
            ],
            [
                'name' => 'Science',
                'slug' => Str::slug('Science'),
                'description' => 'Scientific research, laboratories, and scientific services.',
                'meta_title' => 'Science Jobs',
                'meta_description' => 'Find science and research jobs.',
                'icon' => 'industries/science.png',
                'is_active' => true,
                'sort_order' => 113,
            ],
            [
                'name' => 'Security',
                'slug' => Str::slug('Security'),
                'description' => 'Security services, surveillance, and protection.',
                'meta_title' => 'Security Jobs',
                'meta_description' => 'Find security and protection jobs.',
                'icon' => 'industries/security.png',
                'is_active' => true,
                'sort_order' => 114,
            ],
            [
                'name' => 'Semiconductors',
                'slug' => Str::slug('Semiconductors'),
                'description' => 'Semiconductor manufacturing, chips, and electronics.',
                'meta_title' => 'Semiconductor Jobs',
                'meta_description' => 'Find semiconductor and electronics jobs.',
                'icon' => 'industries/semiconductors.png',
                'is_active' => true,
                'sort_order' => 115,
            ],
            [
                'name' => 'Shipbuilding',
                'slug' => Str::slug('Shipbuilding'),
                'description' => 'Ship construction, marine engineering, and vessels.',
                'meta_title' => 'Shipbuilding Jobs',
                'meta_description' => 'Find shipbuilding and marine jobs.',
                'icon' => 'industries/shipbuilding.png',
                'is_active' => true,
                'sort_order' => 116,
            ],
            [
                'name' => 'Social Services',
                'slug' => Str::slug('Social Services'),
                'description' => 'Community services, social work, and welfare.',
                'meta_title' => 'Social Services Jobs',
                'meta_description' => 'Find social services and community jobs.',
                'icon' => 'industries/social-services.png',
                'is_active' => true,
                'sort_order' => 117,
            ],
            [
                'name' => 'Software Development',
                'slug' => Str::slug('Software Development'),
                'description' => 'Software engineering, programming, and development.',
                'meta_title' => 'Software Development Jobs',
                'meta_description' => 'Find software development and engineering jobs.',
                'icon' => 'industries/software-development.png',
                'is_active' => true,
                'sort_order' => 118,
            ],
            [
                'name' => 'Sports',
                'slug' => Str::slug('Sports'),
                'description' => 'Sports teams, athletics, and sporting events.',
                'meta_title' => 'Sports Jobs',
                'meta_description' => 'Find sports and athletics jobs.',
                'icon' => 'industries/sports.png',
                'is_active' => true,
                'sort_order' => 119,
            ],
            [
                'name' => 'Staffing',
                'slug' => Str::slug('Staffing'),
                'description' => 'Recruitment, staffing services, and employment agencies.',
                'meta_title' => 'Staffing Jobs',
                'meta_description' => 'Find staffing and recruitment jobs.',
                'icon' => 'industries/staffing.png',
                'is_active' => true,
                'sort_order' => 120,
            ],
            [
                'name' => 'Supply Chain',
                'slug' => Str::slug('Supply Chain'),
                'description' => 'Supply chain management, logistics, and operations.',
                'meta_title' => 'Supply Chain Jobs',
                'meta_description' => 'Find supply chain and logistics jobs.',
                'icon' => 'industries/supply-chain.png',
                'is_active' => true,
                'sort_order' => 121,
            ],
            [
                'name' => 'Telecommunications',
                'slug' => Str::slug('Telecommunications'),
                'description' => 'Telecom services, networks, and communications.',
                'meta_title' => 'Telecommunications Jobs',
                'meta_description' => 'Find telecommunications and network jobs.',
                'icon' => 'industries/telecommunications.png',
                'is_active' => true,
                'sort_order' => 122,
            ],
            [
                'name' => 'Textiles',
                'slug' => Str::slug('Textiles'),
                'description' => 'Textile manufacturing, fabrics, and materials.',
                'meta_title' => 'Textiles Jobs',
                'meta_description' => 'Find textiles and fabric jobs.',
                'icon' => 'industries/textiles.png',
                'is_active' => true,
                'sort_order' => 123,
            ],
            [
                'name' => 'Tourism',
                'slug' => Str::slug('Tourism'),
                'description' => 'Travel, tourism services, and destination management.',
                'meta_title' => 'Tourism Jobs',
                'meta_description' => 'Find tourism and travel jobs.',
                'icon' => 'industries/tourism.png',
                'is_active' => true,
                'sort_order' => 124,
            ],
            [
                'name' => 'Transportation',
                'slug' => Str::slug('Transportation'),
                'description' => 'Transport services, shipping, and mobility.',
                'meta_title' => 'Transportation Jobs',
                'meta_description' => 'Find transportation and shipping jobs.',
                'icon' => 'industries/transportation.png',
                'is_active' => true,
                'sort_order' => 125,
            ],
            [
                'name' => 'Travel',
                'slug' => Str::slug('Travel'),
                'description' => 'Travel services, agencies, and hospitality.',
                'meta_title' => 'Travel Jobs',
                'meta_description' => 'Find travel and hospitality jobs.',
                'icon' => 'industries/travel.png',
                'is_active' => true,
                'sort_order' => 126,
            ],
            [
                'name' => 'Utilities',
                'slug' => Str::slug('Utilities'),
                'description' => 'Utility services, power, water, and infrastructure.',
                'meta_title' => 'Utilities Jobs',
                'meta_description' => 'Find utilities and infrastructure jobs.',
                'icon' => 'industries/utilities.png',
                'is_active' => true,
                'sort_order' => 127,
            ],
            [
                'name' => 'Venture Capital',
                'slug' => Str::slug('Venture Capital'),
                'description' => 'Venture capital, startup funding, and investment.',
                'meta_title' => 'Venture Capital Jobs',
                'meta_description' => 'Find venture capital and investment jobs.',
                'icon' => 'industries/venture-capital.png',
                'is_active' => true,
                'sort_order' => 128,
            ],
            [
                'name' => 'Veterinary',
                'slug' => Str::slug('Veterinary'),
                'description' => 'Veterinary services, animal care, and pet health.',
                'meta_title' => 'Veterinary Jobs',
                'meta_description' => 'Find veterinary and animal care jobs.',
                'icon' => 'industries/veterinary.png',
                'is_active' => true,
                'sort_order' => 129,
            ],
            [
                'name' => 'Warehousing',
                'slug' => Str::slug('Warehousing'),
                'description' => 'Storage, distribution, and warehouse operations.',
                'meta_title' => 'Warehousing Jobs',
                'meta_description' => 'Find warehousing and distribution jobs.',
                'icon' => 'industries/warehousing.png',
                'is_active' => true,
                'sort_order' => 130,
            ],
            [
                'name' => 'Waste Management',
                'slug' => Str::slug('Waste Management'),
                'description' => 'Waste collection, disposal, and recycling services.',
                'meta_title' => 'Waste Management Jobs',
                'meta_description' => 'Find waste management and recycling jobs.',
                'icon' => 'industries/waste-management.png',
                'is_active' => true,
                'sort_order' => 131,
            ],
            [
                'name' => 'Water Services',
                'slug' => Str::slug('Water Services'),
                'description' => 'Water supply, treatment, and distribution.',
                'meta_title' => 'Water Services Jobs',
                'meta_description' => 'Find water and utility jobs.',
                'icon' => 'industries/water-services.png',
                'is_active' => true,
                'sort_order' => 132,
            ],
            [
                'name' => 'Wholesale',
                'slug' => Str::slug('Wholesale'),
                'description' => 'Wholesale trade, distribution, and bulk sales.',
                'meta_title' => 'Wholesale Jobs',
                'meta_description' => 'Find wholesale and distribution jobs.',
                'icon' => 'industries/wholesale.png',
                'is_active' => true,
                'sort_order' => 133,
            ],
            [
                'name' => 'Wireless',
                'slug' => Str::slug('Wireless'),
                'description' => 'Wireless communications, mobile, and networks.',
                'meta_title' => 'Wireless Jobs',
                'meta_description' => 'Find wireless and mobile communications jobs.',
                'icon' => 'industries/wireless.png',
                'is_active' => true,
                'sort_order' => 134,
            ],
            [
                'name' => 'Writing',
                'slug' => Str::slug('Writing'),
                'description' => 'Writing, editing, and content creation.',
                'meta_title' => 'Writing Jobs',
                'meta_description' => 'Find writing and editing jobs.',
                'icon' => 'industries/writing.png',
                'is_active' => true,
                'sort_order' => 135,
            ],
        ];

        foreach ($industries as $industry) {
            Industry::create($industry);
        }

        $this->command->info('====================================');
        $this->command->info('INDUSTRY SEEDER COMPLETED SUCCESSFULLY!');
        $this->command->info('====================================');
        $this->command->info('Total industries created: ' . count($industries));
        $this->command->info('====================================');
    }
}
