<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use App\Models\Job\JobCategory;
use Illuminate\Support\Str;

class JobCategorySeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $jobCategories = [
            // Executive & Management
            [
                'name' => 'Executive & Senior Management',
                'slug' => Str::slug('Executive & Senior Management'),
                'description' => 'CEO, CFO, CTO, Directors, Vice Presidents, and other C-suite executive positions.',
                'meta_title' => 'Executive and Senior Management Jobs',
                'meta_description' => 'Find executive and senior management positions including CEO, CFO, Directors, and other leadership roles.',
                'icon' => 'job-categories/executive.png',
                'is_active' => true,
                'sort_order' => 1,
            ],
            [
                'name' => 'Middle Management',
                'slug' => Str::slug('Middle Management'),
                'description' => 'Department managers, team leaders, supervisors, and operations managers.',
                'meta_title' => 'Middle Management Jobs',
                'meta_description' => 'Browse middle management positions including department managers, team leaders, and supervisors.',
                'icon' => 'job-categories/management.png',
                'is_active' => true,
                'sort_order' => 2,
            ],
            [
                'name' => 'Project Management',
                'slug' => Str::slug('Project Management'),
                'description' => 'Project managers, program managers, project coordinators, and agile scrum masters.',
                'meta_title' => 'Project Management Jobs',
                'meta_description' => 'Find project management positions including project managers, program managers, and coordinators.',
                'icon' => 'job-categories/project-management.png',
                'is_active' => true,
                'sort_order' => 3,
            ],

            // Information Technology
            [
                'name' => 'Software Development',
                'slug' => Str::slug('Software Development'),
                'description' => 'Software engineers, developers, programmers, and coding specialists across various languages and platforms.',
                'meta_title' => 'Software Development Jobs',
                'meta_description' => 'Browse software development positions including engineers, developers, and programmers.',
                'icon' => 'job-categories/software-development.png',
                'is_active' => true,
                'sort_order' => 4,
            ],
            [
                'name' => 'Web Development',
                'slug' => Str::slug('Web Development'),
                'description' => 'Frontend developers, backend developers, full-stack developers, and web designers.',
                'meta_title' => 'Web Development Jobs',
                'meta_description' => 'Find web development positions including frontend, backend, and full-stack developers.',
                'icon' => 'job-categories/web-development.png',
                'is_active' => true,
                'sort_order' => 5,
            ],
            [
                'name' => 'Mobile App Development',
                'slug' => Str::slug('Mobile App Development'),
                'description' => 'iOS developers, Android developers, cross-platform developers, and mobile app designers.',
                'meta_title' => 'Mobile App Development Jobs',
                'meta_description' => 'Browse mobile app development positions for iOS, Android, and cross-platform platforms.',
                'icon' => 'job-categories/mobile-dev.png',
                'is_active' => true,
                'sort_order' => 6,
            ],
            [
                'name' => 'DevOps & Cloud Computing',
                'slug' => Str::slug('DevOps & Cloud Computing'),
                'description' => 'DevOps engineers, cloud architects, site reliability engineers, and infrastructure specialists.',
                'meta_title' => 'DevOps and Cloud Computing Jobs',
                'meta_description' => 'Find DevOps, cloud computing, and infrastructure positions.',
                'icon' => 'job-categories/devops.png',
                'is_active' => true,
                'sort_order' => 7,
            ],
            [
                'name' => 'Data Science & Analytics',
                'slug' => Str::slug('Data Science & Analytics'),
                'description' => 'Data scientists, data analysts, business intelligence analysts, and data engineers.',
                'meta_title' => 'Data Science and Analytics Jobs',
                'meta_description' => 'Browse data science, analytics, and business intelligence positions.',
                'icon' => 'job-categories/data-science.png',
                'is_active' => true,
                'sort_order' => 8,
            ],
            [
                'name' => 'Machine Learning & AI',
                'slug' => Str::slug('Machine Learning & AI'),
                'description' => 'Machine learning engineers, AI researchers, NLP engineers, and computer vision specialists.',
                'meta_title' => 'Machine Learning and AI Jobs',
                'meta_description' => 'Find machine learning, artificial intelligence, and research positions.',
                'icon' => 'job-categories/ai-ml.png',
                'is_active' => true,
                'sort_order' => 9,
            ],
            [
                'name' => 'Cybersecurity',
                'slug' => Str::slug('Cybersecurity'),
                'description' => 'Security analysts, ethical hackers, security architects, and information security managers.',
                'meta_title' => 'Cybersecurity Jobs',
                'meta_description' => 'Browse cybersecurity, information security, and network security positions.',
                'icon' => 'job-categories/cybersecurity.png',
                'is_active' => true,
                'sort_order' => 10,
            ],
            [
                'name' => 'IT Support & Helpdesk',
                'slug' => Str::slug('IT Support & Helpdesk'),
                'description' => 'IT support specialists, helpdesk technicians, system administrators, and technical support.',
                'meta_title' => 'IT Support and Helpdesk Jobs',
                'meta_description' => 'Find IT support, helpdesk, and system administration positions.',
                'icon' => 'job-categories/it-support.png',
                'is_active' => true,
                'sort_order' => 11,
            ],
            [
                'name' => 'Database Administration',
                'slug' => Str::slug('Database Administration'),
                'description' => 'Database administrators, data architects, and database developers.',
                'meta_title' => 'Database Administration Jobs',
                'meta_description' => 'Browse database administration and data architecture positions.',
                'icon' => 'job-categories/database.png',
                'is_active' => true,
                'sort_order' => 12,
            ],
            [
                'name' => 'Network Engineering',
                'slug' => Str::slug('Network Engineering'),
                'description' => 'Network engineers, network administrators, and network architects.',
                'meta_title' => 'Network Engineering Jobs',
                'meta_description' => 'Find network engineering and administration positions.',
                'icon' => 'job-categories/network.png',
                'is_active' => true,
                'sort_order' => 13,
            ],

            // Finance & Accounting
            [
                'name' => 'Accounting',
                'slug' => Str::slug('Accounting'),
                'description' => 'Accountants, bookkeepers, auditors, and tax specialists.',
                'meta_title' => 'Accounting Jobs',
                'meta_description' => 'Browse accounting positions including accountants, auditors, and tax specialists.',
                'icon' => 'job-categories/accounting.png',
                'is_active' => true,
                'sort_order' => 14,
            ],
            [
                'name' => 'Finance',
                'slug' => Str::slug('Finance'),
                'description' => 'Financial analysts, finance managers, financial planners, and controllers.',
                'meta_title' => 'Finance Jobs',
                'meta_description' => 'Find finance positions including analysts, managers, and financial planners.',
                'icon' => 'job-categories/finance.png',
                'is_active' => true,
                'sort_order' => 15,
            ],
            [
                'name' => 'Banking',
                'slug' => Str::slug('Banking'),
                'description' => 'Bank tellers, loan officers, relationship managers, and banking operations.',
                'meta_title' => 'Banking Jobs',
                'meta_description' => 'Browse banking positions including tellers, loan officers, and relationship managers.',
                'icon' => 'job-categories/banking.png',
                'is_active' => true,
                'sort_order' => 16,
            ],
            [
                'name' => 'Investment Banking',
                'slug' => Str::slug('Investment Banking'),
                'description' => 'Investment bankers, financial advisors, and capital market specialists.',
                'meta_title' => 'Investment Banking Jobs',
                'meta_description' => 'Find investment banking and capital markets positions.',
                'icon' => 'job-categories/investment-banking.png',
                'is_active' => true,
                'sort_order' => 17,
            ],
            [
                'name' => 'Insurance',
                'slug' => Str::slug('Insurance'),
                'description' => 'Insurance agents, underwriters, claims adjusters, and actuaries.',
                'meta_title' => 'Insurance Jobs',
                'meta_description' => 'Browse insurance positions including agents, underwriters, and claims adjusters.',
                'icon' => 'job-categories/insurance.png',
                'is_active' => true,
                'sort_order' => 18,
            ],
            [
                'name' => 'Auditing',
                'slug' => Str::slug('Auditing'),
                'description' => 'Internal auditors, external auditors, and compliance officers.',
                'meta_title' => 'Auditing Jobs',
                'meta_description' => 'Find auditing and compliance positions.',
                'icon' => 'job-categories/auditing.png',
                'is_active' => true,
                'sort_order' => 19,
            ],

            // Sales & Marketing
            [
                'name' => 'Sales',
                'slug' => Str::slug('Sales'),
                'description' => 'Sales representatives, account executives, business development managers, and sales directors.',
                'meta_title' => 'Sales Jobs',
                'meta_description' => 'Browse sales positions including representatives, account executives, and managers.',
                'icon' => 'job-categories/sales.png',
                'is_active' => true,
                'sort_order' => 20,
            ],
            [
                'name' => 'Marketing',
                'slug' => Str::slug('Marketing'),
                'description' => 'Marketing managers, marketing coordinators, brand managers, and product marketers.',
                'meta_title' => 'Marketing Jobs',
                'meta_description' => 'Find marketing positions including managers, coordinators, and brand specialists.',
                'icon' => 'job-categories/marketing.png',
                'is_active' => true,
                'sort_order' => 21,
            ],
            [
                'name' => 'Digital Marketing',
                'slug' => Str::slug('Digital Marketing'),
                'description' => 'SEO specialists, SEM specialists, digital marketing managers, and online marketers.',
                'meta_title' => 'Digital Marketing Jobs',
                'meta_description' => 'Browse digital marketing positions including SEO, SEM, and online marketing.',
                'icon' => 'job-categories/digital-marketing.png',
                'is_active' => true,
                'sort_order' => 22,
            ],
            [
                'name' => 'Social Media Management',
                'slug' => Str::slug('Social Media Management'),
                'description' => 'Social media managers, content creators, and community managers.',
                'meta_title' => 'Social Media Jobs',
                'meta_description' => 'Find social media management and content creation positions.',
                'icon' => 'job-categories/social-media.png',
                'is_active' => true,
                'sort_order' => 23,
            ],
            [
                'name' => 'Content Marketing',
                'slug' => Str::slug('Content Marketing'),
                'description' => 'Content writers, content strategists, copywriters, and editors.',
                'meta_title' => 'Content Marketing Jobs',
                'meta_description' => 'Browse content marketing, writing, and editing positions.',
                'icon' => 'job-categories/content.png',
                'is_active' => true,
                'sort_order' => 24,
            ],
            [
                'name' => 'Advertising',
                'slug' => Str::slug('Advertising'),
                'description' => 'Advertising managers, account managers, creative directors, and media planners.',
                'meta_title' => 'Advertising Jobs',
                'meta_description' => 'Find advertising and media planning positions.',
                'icon' => 'job-categories/advertising.png',
                'is_active' => true,
                'sort_order' => 25,
            ],
            [
                'name' => 'Public Relations',
                'slug' => Str::slug('Public Relations'),
                'description' => 'PR managers, communications specialists, and media relations officers.',
                'meta_title' => 'Public Relations Jobs',
                'meta_description' => 'Browse public relations and communications positions.',
                'icon' => 'job-categories/pr.png',
                'is_active' => true,
                'sort_order' => 26,
            ],
            [
                'name' => 'Market Research',
                'slug' => Str::slug('Market Research'),
                'description' => 'Market researchers, research analysts, and consumer insights specialists.',
                'meta_title' => 'Market Research Jobs',
                'meta_description' => 'Find market research and consumer insights positions.',
                'icon' => 'job-categories/market-research.png',
                'is_active' => true,
                'sort_order' => 27,
            ],

            // Human Resources
            [
                'name' => 'Human Resources',
                'slug' => Str::slug('Human Resources'),
                'description' => 'HR managers, HR generalists, HR business partners, and personnel officers.',
                'meta_title' => 'Human Resources Jobs',
                'meta_description' => 'Browse human resources positions including managers, generalists, and business partners.',
                'icon' => 'job-categories/hr.png',
                'is_active' => true,
                'sort_order' => 28,
            ],
            [
                'name' => 'Recruitment',
                'slug' => Str::slug('Recruitment'),
                'description' => 'Recruiters, talent acquisition specialists, and headhunters.',
                'meta_title' => 'Recruitment Jobs',
                'meta_description' => 'Find recruitment and talent acquisition positions.',
                'icon' => 'job-categories/recruitment.png',
                'is_active' => true,
                'sort_order' => 29,
            ],
            [
                'name' => 'Training & Development',
                'slug' => Str::slug('Training & Development'),
                'description' => 'Training managers, learning and development specialists, and corporate trainers.',
                'meta_title' => 'Training and Development Jobs',
                'meta_description' => 'Browse training, learning, and development positions.',
                'icon' => 'job-categories/training.png',
                'is_active' => true,
                'sort_order' => 30,
            ],
            [
                'name' => 'Compensation & Benefits',
                'slug' => Str::slug('Compensation & Benefits'),
                'description' => 'Compensation analysts, benefits specialists, and payroll managers.',
                'meta_title' => 'Compensation and Benefits Jobs',
                'meta_description' => 'Find compensation, benefits, and payroll positions.',
                'icon' => 'job-categories/compensation.png',
                'is_active' => true,
                'sort_order' => 31,
            ],

            // Healthcare & Medical
            [
                'name' => 'Medical Doctors',
                'slug' => Str::slug('Medical Doctors'),
                'description' => 'Physicians, surgeons, general practitioners, and medical specialists.',
                'meta_title' => 'Medical Doctor Jobs',
                'meta_description' => 'Browse medical doctor positions including physicians, surgeons, and specialists.',
                'icon' => 'job-categories/doctors.png',
                'is_active' => true,
                'sort_order' => 32,
            ],
            [
                'name' => 'Nursing',
                'slug' => Str::slug('Nursing'),
                'description' => 'Registered nurses, nurse practitioners, and nursing assistants.',
                'meta_title' => 'Nursing Jobs',
                'meta_description' => 'Find nursing positions including registered nurses and nurse practitioners.',
                'icon' => 'job-categories/nursing.png',
                'is_active' => true,
                'sort_order' => 33,
            ],
            [
                'name' => 'Pharmacy',
                'slug' => Str::slug('Pharmacy'),
                'description' => 'Pharmacists, pharmacy technicians, and pharmaceutical specialists.',
                'meta_title' => 'Pharmacy Jobs',
                'meta_description' => 'Browse pharmacy and pharmaceutical positions.',
                'icon' => 'job-categories/pharmacy.png',
                'is_active' => true,
                'sort_order' => 34,
            ],
            [
                'name' => 'Dentistry',
                'slug' => Str::slug('Dentistry'),
                'description' => 'Dentists, dental hygienists, and dental assistants.',
                'meta_title' => 'Dentistry Jobs',
                'meta_description' => 'Find dental and oral healthcare positions.',
                'icon' => 'job-categories/dentistry.png',
                'is_active' => true,
                'sort_order' => 35,
            ],
            [
                'name' => 'Allied Health',
                'slug' => Str::slug('Allied Health'),
                'description' => 'Physiotherapists, occupational therapists, radiographers, and laboratory technicians.',
                'meta_title' => 'Allied Health Jobs',
                'meta_description' => 'Browse allied health and therapy positions.',
                'icon' => 'job-categories/allied-health.png',
                'is_active' => true,
                'sort_order' => 36,
            ],
            [
                'name' => 'Healthcare Administration',
                'slug' => Str::slug('Healthcare Administration'),
                'description' => 'Hospital administrators, healthcare managers, and medical office managers.',
                'meta_title' => 'Healthcare Administration Jobs',
                'meta_description' => 'Find healthcare administration and management positions.',
                'icon' => 'job-categories/health-admin.png',
                'is_active' => true,
                'sort_order' => 37,
            ],
            [
                'name' => 'Mental Health',
                'slug' => Str::slug('Mental Health'),
                'description' => 'Psychologists, psychiatrists, counselors, and therapists.',
                'meta_title' => 'Mental Health Jobs',
                'meta_description' => 'Browse mental health and counseling positions.',
                'icon' => 'job-categories/mental-health.png',
                'is_active' => true,
                'sort_order' => 38,
            ],
            [
                'name' => 'Veterinary',
                'slug' => Str::slug('Veterinary'),
                'description' => 'Veterinarians, veterinary technicians, and animal care specialists.',
                'meta_title' => 'Veterinary Jobs',
                'meta_description' => 'Find veterinary and animal care positions.',
                'icon' => 'job-categories/veterinary.png',
                'is_active' => true,
                'sort_order' => 39,
            ],

            // Engineering
            [
                'name' => 'Civil Engineering',
                'slug' => Str::slug('Civil Engineering'),
                'description' => 'Civil engineers, structural engineers, and construction engineers.',
                'meta_title' => 'Civil Engineering Jobs',
                'meta_description' => 'Browse civil and structural engineering positions.',
                'icon' => 'job-categories/civil-engineering.png',
                'is_active' => true,
                'sort_order' => 40,
            ],
            [
                'name' => 'Mechanical Engineering',
                'slug' => Str::slug('Mechanical Engineering'),
                'description' => 'Mechanical engineers, HVAC engineers, and maintenance engineers.',
                'meta_title' => 'Mechanical Engineering Jobs',
                'meta_description' => 'Find mechanical and maintenance engineering positions.',
                'icon' => 'job-categories/mechanical-engineering.png',
                'is_active' => true,
                'sort_order' => 41,
            ],
            [
                'name' => 'Electrical Engineering',
                'slug' => Str::slug('Electrical Engineering'),
                'description' => 'Electrical engineers, electronics engineers, and power engineers.',
                'meta_title' => 'Electrical Engineering Jobs',
                'meta_description' => 'Browse electrical and electronics engineering positions.',
                'icon' => 'job-categories/electrical-engineering.png',
                'is_active' => true,
                'sort_order' => 42,
            ],
            [
                'name' => 'Chemical Engineering',
                'slug' => Str::slug('Chemical Engineering'),
                'description' => 'Chemical engineers, process engineers, and materials engineers.',
                'meta_title' => 'Chemical Engineering Jobs',
                'meta_description' => 'Find chemical and process engineering positions.',
                'icon' => 'job-categories/chemical-engineering.png',
                'is_active' => true,
                'sort_order' => 43,
            ],
            [
                'name' => 'Industrial Engineering',
                'slug' => Str::slug('Industrial Engineering'),
                'description' => 'Industrial engineers, manufacturing engineers, and quality engineers.',
                'meta_title' => 'Industrial Engineering Jobs',
                'meta_description' => 'Browse industrial and manufacturing engineering positions.',
                'icon' => 'job-categories/industrial-engineering.png',
                'is_active' => true,
                'sort_order' => 44,
            ],
            [
                'name' => 'Environmental Engineering',
                'slug' => Str::slug('Environmental Engineering'),
                'description' => 'Environmental engineers, sustainability engineers, and waste management specialists.',
                'meta_title' => 'Environmental Engineering Jobs',
                'meta_description' => 'Find environmental and sustainability engineering positions.',
                'icon' => 'job-categories/environmental-engineering.png',
                'is_active' => true,
                'sort_order' => 45,
            ],
            [
                'name' => 'Biomedical Engineering',
                'slug' => Str::slug('Biomedical Engineering'),
                'description' => 'Biomedical engineers, medical device engineers, and healthcare technology specialists.',
                'meta_title' => 'Biomedical Engineering Jobs',
                'meta_description' => 'Browse biomedical and medical device engineering positions.',
                'icon' => 'job-categories/biomedical-engineering.png',
                'is_active' => true,
                'sort_order' => 46,
            ],

            // Construction & Trades
            [
                'name' => 'Construction',
                'slug' => Str::slug('Construction'),
                'description' => 'Construction managers, site supervisors, and construction workers.',
                'meta_title' => 'Construction Jobs',
                'meta_description' => 'Find construction and site management positions.',
                'icon' => 'job-categories/construction.png',
                'is_active' => true,
                'sort_order' => 47,
            ],
            [
                'name' => 'Architecture',
                'slug' => Str::slug('Architecture'),
                'description' => 'Architects, architectural designers, and urban planners.',
                'meta_title' => 'Architecture Jobs',
                'meta_description' => 'Browse architecture and design positions.',
                'icon' => 'job-categories/architecture.png',
                'is_active' => true,
                'sort_order' => 48,
            ],
            [
                'name' => 'Surveying',
                'slug' => Str::slug('Surveying'),
                'description' => 'Land surveyors, quantity surveyors, and geomatics specialists.',
                'meta_title' => 'Surveying Jobs',
                'meta_description' => 'Find land and quantity surveying positions.',
                'icon' => 'job-categories/surveying.png',
                'is_active' => true,
                'sort_order' => 49,
            ],
            [
                'name' => 'Electrician',
                'slug' => Str::slug('Electrician'),
                'description' => 'Electricians, electrical technicians, and wiring specialists.',
                'meta_title' => 'Electrician Jobs',
                'meta_description' => 'Browse electrical and wiring positions.',
                'icon' => 'job-categories/electrician.png',
                'is_active' => true,
                'sort_order' => 50,
            ],
            [
                'name' => 'Plumbing',
                'slug' => Str::slug('Plumbing'),
                'description' => 'Plumbers, pipe fitters, and plumbing technicians.',
                'meta_title' => 'Plumbing Jobs',
                'meta_description' => 'Find plumbing and pipe fitting positions.',
                'icon' => 'job-categories/plumbing.png',
                'is_active' => true,
                'sort_order' => 51,
            ],
            [
                'name' => 'Carpentry',
                'slug' => Str::slug('Carpentry'),
                'description' => 'Carpenters, joiners, and woodworkers.',
                'meta_title' => 'Carpentry Jobs',
                'meta_description' => 'Browse carpentry and woodworking positions.',
                'icon' => 'job-categories/carpentry.png',
                'is_active' => true,
                'sort_order' => 52,
            ],
            [
                'name' => 'Masonry',
                'slug' => Str::slug('Masonry'),
                'description' => 'Masons, bricklayers, and concrete workers.',
                'meta_title' => 'Masonry Jobs',
                'meta_description' => 'Find masonry and bricklaying positions.',
                'icon' => 'job-categories/masonry.png',
                'is_active' => true,
                'sort_order' => 53,
            ],
            [
                'name' => 'Welding',
                'slug' => Str::slug('Welding'),
                'description' => 'Welders, fabricators, and metal workers.',
                'meta_title' => 'Welding Jobs',
                'meta_description' => 'Browse welding and metal fabrication positions.',
                'icon' => 'job-categories/welding.png',
                'is_active' => true,
                'sort_order' => 54,
            ],

            // Education & Training
            [
                'name' => 'Teaching',
                'slug' => Str::slug('Teaching'),
                'description' => 'Teachers, classroom instructors, and educators at all levels.',
                'meta_title' => 'Teaching Jobs',
                'meta_description' => 'Find teaching and education positions.',
                'icon' => 'job-categories/teaching.png',
                'is_active' => true,
                'sort_order' => 55,
            ],
            [
                'name' => 'University Faculty',
                'slug' => Str::slug('University Faculty'),
                'description' => 'Professors, lecturers, researchers, and academic faculty.',
                'meta_title' => 'University Faculty Jobs',
                'meta_description' => 'Browse university and college faculty positions.',
                'icon' => 'job-categories/university.png',
                'is_active' => true,
                'sort_order' => 56,
            ],
            [
                'name' => 'Early Childhood Education',
                'slug' => Str::slug('Early Childhood Education'),
                'description' => 'Preschool teachers, daycare providers, and early childhood educators.',
                'meta_title' => 'Early Childhood Education Jobs',
                'meta_description' => 'Find early childhood and preschool teaching positions.',
                'icon' => 'job-categories/early-childhood.png',
                'is_active' => true,
                'sort_order' => 57,
            ],
            [
                'name' => 'Special Education',
                'slug' => Str::slug('Special Education'),
                'description' => 'Special education teachers, learning support specialists, and interventionists.',
                'meta_title' => 'Special Education Jobs',
                'meta_description' => 'Browse special education and learning support positions.',
                'icon' => 'job-categories/special-education.png',
                'is_active' => true,
                'sort_order' => 58,
            ],
            [
                'name' => 'Curriculum Development',
                'slug' => Str::slug('Curriculum Development'),
                'description' => 'Curriculum designers, instructional coordinators, and educational consultants.',
                'meta_title' => 'Curriculum Development Jobs',
                'meta_description' => 'Find curriculum design and instructional coordination positions.',
                'icon' => 'job-categories/curriculum.png',
                'is_active' => true,
                'sort_order' => 59,
            ],
            [
                'name' => 'E-Learning',
                'slug' => Str::slug('E-Learning'),
                'description' => 'E-learning developers, instructional designers, and online educators.',
                'meta_title' => 'E-Learning Jobs',
                'meta_description' => 'Browse e-learning and online education positions.',
                'icon' => 'job-categories/elearning.png',
                'is_active' => true,
                'sort_order' => 60,
            ],

            // Hospitality & Tourism
            [
                'name' => 'Hotel Management',
                'slug' => Str::slug('Hotel Management'),
                'description' => 'Hotel managers, front office managers, and hospitality supervisors.',
                'meta_title' => 'Hotel Management Jobs',
                'meta_description' => 'Find hotel and hospitality management positions.',
                'icon' => 'job-categories/hotel-management.png',
                'is_active' => true,
                'sort_order' => 61,
            ],
            [
                'name' => 'Food & Beverage',
                'slug' => Str::slug('Food & Beverage'),
                'description' => 'Chefs, cooks, waiters, bartenders, and restaurant staff.',
                'meta_title' => 'Food and Beverage Jobs',
                'meta_description' => 'Browse food service, restaurant, and catering positions.',
                'icon' => 'job-categories/food-beverage.png',
                'is_active' => true,
                'sort_order' => 62,
            ],
            [
                'name' => 'Tourism',
                'slug' => Str::slug('Tourism'),
                'description' => 'Tour guides, travel agents, and tourism officers.',
                'meta_title' => 'Tourism Jobs',
                'meta_description' => 'Find tourism and travel industry positions.',
                'icon' => 'job-categories/tourism.png',
                'is_active' => true,
                'sort_order' => 63,
            ],
            [
                'name' => 'Event Management',
                'slug' => Str::slug('Event Management'),
                'description' => 'Event planners, coordinators, and wedding planners.',
                'meta_title' => 'Event Management Jobs',
                'meta_description' => 'Browse event planning and coordination positions.',
                'icon' => 'job-categories/event-management.png',
                'is_active' => true,
                'sort_order' => 64,
            ],
            [
                'name' => 'Travel Services',
                'slug' => Str::slug('Travel Services'),
                'description' => 'Travel consultants, reservation agents, and travel coordinators.',
                'meta_title' => 'Travel Services Jobs',
                'meta_description' => 'Find travel and reservation positions.',
                'icon' => 'job-categories/travel.png',
                'is_active' => true,
                'sort_order' => 65,
            ],

            // Logistics & Transportation
            [
                'name' => 'Logistics',
                'slug' => Str::slug('Logistics'),
                'description' => 'Logistics coordinators, supply chain managers, and operations specialists.',
                'meta_title' => 'Logistics Jobs',
                'meta_description' => 'Find logistics and supply chain positions.',
                'icon' => 'job-categories/logistics.png',
                'is_active' => true,
                'sort_order' => 66,
            ],
            [
                'name' => 'Supply Chain',
                'slug' => Str::slug('Supply Chain'),
                'description' => 'Supply chain managers, procurement officers, and inventory specialists.',
                'meta_title' => 'Supply Chain Jobs',
                'meta_description' => 'Browse supply chain and procurement positions.',
                'icon' => 'job-categories/supply-chain.png',
                'is_active' => true,
                'sort_order' => 67,
            ],
            [
                'name' => 'Procurement',
                'slug' => Str::slug('Procurement'),
                'description' => 'Procurement officers, buyers, and purchasing managers.',
                'meta_title' => 'Procurement Jobs',
                'meta_description' => 'Find procurement and purchasing positions.',
                'icon' => 'job-categories/procurement.png',
                'is_active' => true,
                'sort_order' => 68,
            ],
            [
                'name' => 'Warehousing',
                'slug' => Str::slug('Warehousing'),
                'description' => 'Warehouse managers, storekeepers, and inventory controllers.',
                'meta_title' => 'Warehousing Jobs',
                'meta_description' => 'Browse warehouse and inventory management positions.',
                'icon' => 'job-categories/warehousing.png',
                'is_active' => true,
                'sort_order' => 69,
            ],
            [
                'name' => 'Transportation',
                'slug' => Str::slug('Transportation'),
                'description' => 'Drivers, dispatchers, and transportation coordinators.',
                'meta_title' => 'Transportation Jobs',
                'meta_description' => 'Find driving and transportation positions.',
                'icon' => 'job-categories/transportation.png',
                'is_active' => true,
                'sort_order' => 70,
            ],
            [
                'name' => 'Fleet Management',
                'slug' => Str::slug('Fleet Management'),
                'description' => 'Fleet managers, vehicle coordinators, and transport supervisors.',
                'meta_title' => 'Fleet Management Jobs',
                'meta_description' => 'Browse fleet and vehicle management positions.',
                'icon' => 'job-categories/fleet.png',
                'is_active' => true,
                'sort_order' => 71,
            ],

            // Creative & Design
            [
                'name' => 'Graphic Design',
                'slug' => Str::slug('Graphic Design'),
                'description' => 'Graphic designers, visual designers, and creative artists.',
                'meta_title' => 'Graphic Design Jobs',
                'meta_description' => 'Find graphic design and visual arts positions.',
                'icon' => 'job-categories/graphic-design.png',
                'is_active' => true,
                'sort_order' => 72,
            ],
            [
                'name' => 'UX/UI Design',
                'slug' => Str::slug('UX/UI Design'),
                'description' => 'UX designers, UI designers, and product designers.',
                'meta_title' => 'UX/UI Design Jobs',
                'meta_description' => 'Browse user experience and interface design positions.',
                'icon' => 'job-categories/ux-ui.png',
                'is_active' => true,
                'sort_order' => 73,
            ],
            [
                'name' => 'Product Design',
                'slug' => Str::slug('Product Design'),
                'description' => 'Product designers, industrial designers, and design engineers.',
                'meta_title' => 'Product Design Jobs',
                'meta_description' => 'Find product and industrial design positions.',
                'icon' => 'job-categories/product-design.png',
                'is_active' => true,
                'sort_order' => 74,
            ],
            [
                'name' => 'Fashion Design',
                'slug' => Str::slug('Fashion Design'),
                'description' => 'Fashion designers, textile designers, and clothing manufacturers.',
                'meta_title' => 'Fashion Design Jobs',
                'meta_description' => 'Browse fashion and textile design positions.',
                'icon' => 'job-categories/fashion.png',
                'is_active' => true,
                'sort_order' => 75,
            ],
            [
                'name' => 'Interior Design',
                'slug' => Str::slug('Interior Design'),
                'description' => 'Interior designers, decorators, and space planners.',
                'meta_title' => 'Interior Design Jobs',
                'meta_description' => 'Find interior design and decoration positions.',
                'icon' => 'job-categories/interior-design.png',
                'is_active' => true,
                'sort_order' => 76,
            ],
            [
                'name' => 'Photography',
                'slug' => Str::slug('Photography'),
                'description' => 'Photographers, videographers, and photo editors.',
                'meta_title' => 'Photography Jobs',
                'meta_description' => 'Browse photography and videography positions.',
                'icon' => 'job-categories/photography.png',
                'is_active' => true,
                'sort_order' => 77,
            ],
            [
                'name' => 'Animation',
                'slug' => Str::slug('Animation'),
                'description' => 'Animators, motion graphics designers, and 3D artists.',
                'meta_title' => 'Animation Jobs',
                'meta_description' => 'Find animation and motion graphics positions.',
                'icon' => 'job-categories/animation.png',
                'is_active' => true,
                'sort_order' => 78,
            ],

            // Media & Communications
            [
                'name' => 'Journalism',
                'slug' => Str::slug('Journalism'),
                'description' => 'Journalists, reporters, correspondents, and news writers.',
                'meta_title' => 'Journalism Jobs',
                'meta_description' => 'Browse journalism and reporting positions.',
                'icon' => 'job-categories/journalism.png',
                'is_active' => true,
                'sort_order' => 79,
            ],
            [
                'name' => 'Broadcasting',
                'slug' => Str::slug('Broadcasting'),
                'description' => 'Radio hosts, TV presenters, and broadcast journalists.',
                'meta_title' => 'Broadcasting Jobs',
                'meta_description' => 'Find broadcasting and media presentation positions.',
                'icon' => 'job-categories/broadcasting.png',
                'is_active' => true,
                'sort_order' => 80,
            ],
            [
                'name' => 'Publishing',
                'slug' => Str::slug('Publishing'),
                'description' => 'Editors, publishers, and publishing professionals.',
                'meta_title' => 'Publishing Jobs',
                'meta_description' => 'Browse publishing and editorial positions.',
                'icon' => 'job-categories/publishing.png',
                'is_active' => true,
                'sort_order' => 81,
            ],
            [
                'name' => 'Writing',
                'slug' => Str::slug('Writing'),
                'description' => 'Writers, authors, copywriters, and content creators.',
                'meta_title' => 'Writing Jobs',
                'meta_description' => 'Find writing and content creation positions.',
                'icon' => 'job-categories/writing.png',
                'is_active' => true,
                'sort_order' => 82,
            ],

            // Legal
            [
                'name' => 'Legal',
                'slug' => Str::slug('Legal'),
                'description' => 'Lawyers, attorneys, and legal practitioners.',
                'meta_title' => 'Legal Jobs',
                'meta_description' => 'Find legal and law practice positions.',
                'icon' => 'job-categories/legal.png',
                'is_active' => true,
                'sort_order' => 83,
            ],
            [
                'name' => 'Paralegal',
                'slug' => Str::slug('Paralegal'),
                'description' => 'Paralegals, legal assistants, and legal support staff.',
                'meta_title' => 'Paralegal Jobs',
                'meta_description' => 'Browse paralegal and legal support positions.',
                'icon' => 'job-categories/paralegal.png',
                'is_active' => true,
                'sort_order' => 84,
            ],
            [
                'name' => 'Corporate Law',
                'slug' => Str::slug('Corporate Law'),
                'description' => 'Corporate lawyers, in-house counsel, and legal advisors.',
                'meta_title' => 'Corporate Law Jobs',
                'meta_description' => 'Find corporate and business law positions.',
                'icon' => 'job-categories/corporate-law.png',
                'is_active' => true,
                'sort_order' => 85,
            ],

            // Science & Research
            [
                'name' => 'Research',
                'slug' => Str::slug('Research'),
                'description' => 'Research scientists, research assistants, and laboratory researchers.',
                'meta_title' => 'Research Jobs',
                'meta_description' => 'Browse scientific research and laboratory positions.',
                'icon' => 'job-categories/research.png',
                'is_active' => true,
                'sort_order' => 86,
            ],
            [
                'name' => 'Laboratory',
                'slug' => Str::slug('Laboratory'),
                'description' => 'Lab technicians, lab assistants, and laboratory managers.',
                'meta_title' => 'Laboratory Jobs',
                'meta_description' => 'Find laboratory and testing positions.',
                'icon' => 'job-categories/laboratory.png',
                'is_active' => true,
                'sort_order' => 87,
            ],
            [
                'name' => 'Biology',
                'slug' => Str::slug('Biology'),
                'description' => 'Biologists, microbiologists, and life scientists.',
                'meta_title' => 'Biology Jobs',
                'meta_description' => 'Browse biology and life science positions.',
                'icon' => 'job-categories/biology.png',
                'is_active' => true,
                'sort_order' => 88,
            ],
            [
                'name' => 'Chemistry',
                'slug' => Str::slug('Chemistry'),
                'description' => 'Chemists, analytical chemists, and chemical scientists.',
                'meta_title' => 'Chemistry Jobs',
                'meta_description' => 'Find chemistry and chemical analysis positions.',
                'icon' => 'job-categories/chemistry.png',
                'is_active' => true,
                'sort_order' => 89,
            ],
            [
                'name' => 'Physics',
                'slug' => Str::slug('Physics'),
                'description' => 'Physicists, nuclear scientists, and physical science researchers.',
                'meta_title' => 'Physics Jobs',
                'meta_description' => 'Browse physics and physical science positions.',
                'icon' => 'job-categories/physics.png',
                'is_active' => true,
                'sort_order' => 90,
            ],

            // Agriculture & Environment
            [
                'name' => 'Agriculture',
                'slug' => Str::slug('Agriculture'),
                'description' => 'Farmers, agricultural officers, and agronomists.',
                'meta_title' => 'Agriculture Jobs',
                'meta_description' => 'Find agriculture and farming positions.',
                'icon' => 'job-categories/agriculture.png',
                'is_active' => true,
                'sort_order' => 91,
            ],
            [
                'name' => 'Agronomy',
                'slug' => Str::slug('Agronomy'),
                'description' => 'Agronomists, crop scientists, and soil scientists.',
                'meta_title' => 'Agronomy Jobs',
                'meta_description' => 'Browse agronomy and crop science positions.',
                'icon' => 'job-categories/agronomy.png',
                'is_active' => true,
                'sort_order' => 92,
            ],
            [
                'name' => 'Environmental Science',
                'slug' => Str::slug('Environmental Science'),
                'description' => 'Environmental scientists, ecologists, and conservationists.',
                'meta_title' => 'Environmental Science Jobs',
                'meta_description' => 'Find environmental and conservation positions.',
                'icon' => 'job-categories/environmental.png',
                'is_active' => true,
                'sort_order' => 93,
            ],
            [
                'name' => 'Forestry',
                'slug' => Str::slug('Forestry'),
                'description' => 'Foresters, forest rangers, and timber specialists.',
                'meta_title' => 'Forestry Jobs',
                'meta_description' => 'Browse forestry and forest management positions.',
                'icon' => 'job-categories/forestry.png',
                'is_active' => true,
                'sort_order' => 94,
            ],

            // Customer Service
            [
                'name' => 'Customer Service',
                'slug' => Str::slug('Customer Service'),
                'description' => 'Customer service representatives, support agents, and client service officers.',
                'meta_title' => 'Customer Service Jobs',
                'meta_description' => 'Find customer service and support positions.',
                'icon' => 'job-categories/customer-service.png',
                'is_active' => true,
                'sort_order' => 95,
            ],
            [
                'name' => 'Call Center',
                'slug' => Str::slug('Call Center'),
                'description' => 'Call center agents, telemarketers, and phone support staff.',
                'meta_title' => 'Call Center Jobs',
                'meta_description' => 'Browse call center and phone support positions.',
                'icon' => 'job-categories/call-center.png',
                'is_active' => true,
                'sort_order' => 96,
            ],
            [
                'name' => 'Client Relations',
                'slug' => Str::slug('Client Relations'),
                'description' => 'Client relationship managers, account managers, and customer success specialists.',
                'meta_title' => 'Client Relations Jobs',
                'meta_description' => 'Find client relations and customer success positions.',
                'icon' => 'job-categories/client-relations.png',
                'is_active' => true,
                'sort_order' => 97,
            ],

            // Administrative
            [
                'name' => 'Administration',
                'slug' => Str::slug('Administration'),
                'description' => 'Administrative assistants, office managers, and administrative officers.',
                'meta_title' => 'Administration Jobs',
                'meta_description' => 'Find administrative and office support positions.',
                'icon' => 'job-categories/administration.png',
                'is_active' => true,
                'sort_order' => 98,
            ],
            [
                'name' => 'Secretarial',
                'slug' => Str::slug('Secretarial'),
                'description' => 'Secretaries, executive assistants, and personal assistants.',
                'meta_title' => 'Secretarial Jobs',
                'meta_description' => 'Browse secretarial and executive assistant positions.',
                'icon' => 'job-categories/secretarial.png',
                'is_active' => true,
                'sort_order' => 99,
            ],
            [
                'name' => 'Office Management',
                'slug' => Str::slug('Office Management'),
                'description' => 'Office managers, facilities managers, and administrative managers.',
                'meta_title' => 'Office Management Jobs',
                'meta_description' => 'Find office and facilities management positions.',
                'icon' => 'job-categories/office-management.png',
                'is_active' => true,
                'sort_order' => 100,
            ],
            [
                'name' => 'Data Entry',
                'slug' => Str::slug('Data Entry'),
                'description' => 'Data entry clerks, typists, and data processors.',
                'meta_title' => 'Data Entry Jobs',
                'meta_description' => 'Browse data entry and processing positions.',
                'icon' => 'job-categories/data-entry.png',
                'is_active' => true,
                'sort_order' => 101,
            ],

            // Security & Protection
            [
                'name' => 'Security',
                'slug' => Str::slug('Security'),
                'description' => 'Security guards, security officers, and surveillance personnel.',
                'meta_title' => 'Security Jobs',
                'meta_description' => 'Find security and protection positions.',
                'icon' => 'job-categories/security.png',
                'is_active' => true,
                'sort_order' => 102,
            ],
            [
                'name' => 'Law Enforcement',
                'slug' => Str::slug('Law Enforcement'),
                'description' => 'Police officers, investigators, and law enforcement personnel.',
                'meta_title' => 'Law Enforcement Jobs',
                'meta_description' => 'Browse law enforcement and investigation positions.',
                'icon' => 'job-categories/law-enforcement.png',
                'is_active' => true,
                'sort_order' => 103,
            ],
            [
                'name' => 'Firefighting',
                'slug' => Str::slug('Firefighting'),
                'description' => 'Firefighters, fire marshals, and emergency responders.',
                'meta_title' => 'Firefighting Jobs',
                'meta_description' => 'Find firefighting and emergency response positions.',
                'icon' => 'job-categories/firefighting.png',
                'is_active' => true,
                'sort_order' => 104,
            ],

            // Sports & Recreation
            [
                'name' => 'Sports',
                'slug' => Str::slug('Sports'),
                'description' => 'Athletes, coaches, trainers, and sports officials.',
                'meta_title' => 'Sports Jobs',
                'meta_description' => 'Browse sports and athletics positions.',
                'icon' => 'job-categories/sports.png',
                'is_active' => true,
                'sort_order' => 105,
            ],
            [
                'name' => 'Fitness',
                'slug' => Str::slug('Fitness'),
                'description' => 'Personal trainers, fitness instructors, and gym managers.',
                'meta_title' => 'Fitness Jobs',
                'meta_description' => 'Find fitness and wellness positions.',
                'icon' => 'job-categories/fitness.png',
                'is_active' => true,
                'sort_order' => 106,
            ],
            [
                'name' => 'Recreation',
                'slug' => Str::slug('Recreation'),
                'description' => 'Recreation coordinators, activity directors, and leisure specialists.',
                'meta_title' => 'Recreation Jobs',
                'meta_description' => 'Browse recreation and leisure positions.',
                'icon' => 'job-categories/recreation.png',
                'is_active' => true,
                'sort_order' => 107,
            ],

            // Nonprofit & Social Services
            [
                'name' => 'Nonprofit',
                'slug' => Str::slug('Nonprofit'),
                'description' => 'Nonprofit managers, program officers, and NGO workers.',
                'meta_title' => 'Nonprofit Jobs',
                'meta_description' => 'Find nonprofit and NGO positions.',
                'icon' => 'job-categories/nonprofit.png',
                'is_active' => true,
                'sort_order' => 108,
            ],
            [
                'name' => 'Social Work',
                'slug' => Str::slug('Social Work'),
                'description' => 'Social workers, case workers, and community service officers.',
                'meta_title' => 'Social Work Jobs',
                'meta_description' => 'Browse social work and community service positions.',
                'icon' => 'job-categories/social-work.png',
                'is_active' => true,
                'sort_order' => 109,
            ],
            [
                'name' => 'Community Development',
                'slug' => Str::slug('Community Development'),
                'description' => 'Community development officers, project coordinators, and outreach workers.',
                'meta_title' => 'Community Development Jobs',
                'meta_description' => 'Find community development and outreach positions.',
                'icon' => 'job-categories/community.png',
                'is_active' => true,
                'sort_order' => 110,
            ],

            // Government & Public Sector
            [
                'name' => 'Government',
                'slug' => Str::slug('Government'),
                'description' => 'Government officials, civil servants, and public administrators.',
                'meta_title' => 'Government Jobs',
                'meta_description' => 'Browse government and public sector positions.',
                'icon' => 'job-categories/government.png',
                'is_active' => true,
                'sort_order' => 111,
            ],
            [
                'name' => 'Public Administration',
                'slug' => Str::slug('Public Administration'),
                'description' => 'Administrators, policy analysts, and public service managers.',
                'meta_title' => 'Public Administration Jobs',
                'meta_description' => 'Find public administration and policy positions.',
                'icon' => 'job-categories/public-admin.png',
                'is_active' => true,
                'sort_order' => 112,
            ],
            [
                'name' => 'Diplomacy',
                'slug' => Str::slug('Diplomacy'),
                'description' => 'Diplomats, foreign service officers, and international relations specialists.',
                'meta_title' => 'Diplomacy Jobs',
                'meta_description' => 'Browse diplomatic and foreign service positions.',
                'icon' => 'job-categories/diplomacy.png',
                'is_active' => true,
                'sort_order' => 113,
            ],

            // Trades & Services
            [
                'name' => 'Driving',
                'slug' => Str::slug('Driving'),
                'description' => 'Drivers, chauffeurs, and delivery drivers.',
                'meta_title' => 'Driving Jobs',
                'meta_description' => 'Find driving and chauffeuring positions.',
                'icon' => 'job-categories/driving.png',
                'is_active' => true,
                'sort_order' => 114,
            ],
            [
                'name' => 'Cleaning',
                'slug' => Str::slug('Cleaning'),
                'description' => 'Cleaners, housekeepers, and janitorial staff.',
                'meta_title' => 'Cleaning Jobs',
                'meta_description' => 'Browse cleaning and housekeeping positions.',
                'icon' => 'job-categories/cleaning.png',
                'is_active' => true,
                'sort_order' => 115,
            ],
            [
                'name' => 'Maintenance',
                'slug' => Str::slug('Maintenance'),
                'description' => 'Maintenance technicians, repairmen, and general maintenance staff.',
                'meta_title' => 'Maintenance Jobs',
                'meta_description' => 'Find maintenance and repair positions.',
                'icon' => 'job-categories/maintenance.png',
                'is_active' => true,
                'sort_order' => 116,
            ],
            [
                'name' => 'Hair & Beauty',
                'slug' => Str::slug('Hair & Beauty'),
                'description' => 'Hair stylists, beauticians, and salon staff.',
                'meta_title' => 'Hair and Beauty Jobs',
                'meta_description' => 'Browse hair styling and beauty positions.',
                'icon' => 'job-categories/hair-beauty.png',
                'is_active' => true,
                'sort_order' => 117,
            ],

            // Manufacturing & Production
            [
                'name' => 'Manufacturing',
                'slug' => Str::slug('Manufacturing'),
                'description' => 'Production workers, machine operators, and manufacturing staff.',
                'meta_title' => 'Manufacturing Jobs',
                'meta_description' => 'Find manufacturing and production positions.',
                'icon' => 'job-categories/manufacturing.png',
                'is_active' => true,
                'sort_order' => 118,
            ],
            [
                'name' => 'Quality Control',
                'slug' => Str::slug('Quality Control'),
                'description' => 'Quality inspectors, quality assurance officers, and testers.',
                'meta_title' => 'Quality Control Jobs',
                'meta_description' => 'Browse quality control and assurance positions.',
                'icon' => 'job-categories/quality-control.png',
                'is_active' => true,
                'sort_order' => 119,
            ],
            [
                'name' => 'Assembly',
                'slug' => Str::slug('Assembly'),
                'description' => 'Assembly line workers, assemblers, and production line staff.',
                'meta_title' => 'Assembly Jobs',
                'meta_description' => 'Find assembly and production line positions.',
                'icon' => 'job-categories/assembly.png',
                'is_active' => true,
                'sort_order' => 120,
            ],

            // Energy & Utilities
            [
                'name' => 'Energy',
                'slug' => Str::slug('Energy'),
                'description' => 'Energy specialists, power plant operators, and utility workers.',
                'meta_title' => 'Energy Jobs',
                'meta_description' => 'Find energy and utilities positions.',
                'icon' => 'job-categories/energy.png',
                'is_active' => true,
                'sort_order' => 121,
            ],
            [
                'name' => 'Oil & Gas',
                'slug' => Str::slug('Oil & Gas'),
                'description' => 'Oil and gas workers, petroleum engineers, and refinery operators.',
                'meta_title' => 'Oil and Gas Jobs',
                'meta_description' => 'Browse oil, gas, and petroleum positions.',
                'icon' => 'job-categories/oil-gas.png',
                'is_active' => true,
                'sort_order' => 122,
            ],
            [
                'name' => 'Renewable Energy',
                'slug' => Str::slug('Renewable Energy'),
                'description' => 'Solar installers, wind technicians, and renewable energy specialists.',
                'meta_title' => 'Renewable Energy Jobs',
                'meta_description' => 'Find solar, wind, and renewable energy positions.',
                'icon' => 'job-categories/renewable.png',
                'is_active' => true,
                'sort_order' => 123,
            ],

            // Real Estate & Property
            [
                'name' => 'Real Estate',
                'slug' => Str::slug('Real Estate'),
                'description' => 'Real estate agents, property managers, and real estate brokers.',
                'meta_title' => 'Real Estate Jobs',
                'meta_description' => 'Browse real estate and property positions.',
                'icon' => 'job-categories/real-estate.png',
                'is_active' => true,
                'sort_order' => 124,
            ],
            [
                'name' => 'Property Management',
                'slug' => Str::slug('Property Management'),
                'description' => 'Property managers, facilities managers, and estate managers.',
                'meta_title' => 'Property Management Jobs',
                'meta_description' => 'Find property and facilities management positions.',
                'icon' => 'job-categories/property.png',
                'is_active' => true,
                'sort_order' => 125,
            ],

            // Entry Level & Internships
            [
                'name' => 'Entry Level',
                'slug' => Str::slug('Entry Level'),
                'description' => 'Entry-level positions, graduate trainee programs, and junior roles.',
                'meta_title' => 'Entry Level Jobs',
                'meta_description' => 'Find entry-level and graduate positions.',
                'icon' => 'job-categories/entry-level.png',
                'is_active' => true,
                'sort_order' => 126,
            ],
            [
                'name' => 'Internship',
                'slug' => Str::slug('Internship'),
                'description' => 'Internships, industrial attachments, and trainee positions.',
                'meta_title' => 'Internships',
                'meta_description' => 'Browse internship and trainee positions.',
                'icon' => 'job-categories/internship.png',
                'is_active' => true,
                'sort_order' => 127,
            ],
            [
                'name' => 'Apprenticeship',
                'slug' => Str::slug('Apprenticeship'),
                'description' => 'Apprenticeships, vocational training, and learn-on-the-job programs.',
                'meta_title' => 'Apprenticeships',
                'meta_description' => 'Find apprenticeship and vocational training positions.',
                'icon' => 'job-categories/apprenticeship.png',
                'is_active' => true,
                'sort_order' => 128,
            ],

            // Remote & Freelance
            [
                'name' => 'Remote Work',
                'slug' => Str::slug('Remote Work'),
                'description' => 'Remote positions, work-from-home jobs, and virtual roles.',
                'meta_title' => 'Remote Jobs',
                'meta_description' => 'Find remote and work-from-home positions.',
                'icon' => 'job-categories/remote.png',
                'is_active' => true,
                'sort_order' => 129,
            ],
            [
                'name' => 'Freelance',
                'slug' => Str::slug('Freelance'),
                'description' => 'Freelance opportunities, contract work, and independent contracting.',
                'meta_title' => 'Freelance Jobs',
                'meta_description' => 'Browse freelance and contract positions.',
                'icon' => 'job-categories/freelance.png',
                'is_active' => true,
                'sort_order' => 130,
            ],
            [
                'name' => 'Contract',
                'slug' => Str::slug('Contract'),
                'description' => 'Contract positions, fixed-term roles, and project-based work.',
                'meta_title' => 'Contract Jobs',
                'meta_description' => 'Find contract and project-based positions.',
                'icon' => 'job-categories/contract.png',
                'is_active' => true,
                'sort_order' => 131,
            ],

            // Part Time & Temporary
            [
                'name' => 'Part Time',
                'slug' => Str::slug('Part Time'),
                'description' => 'Part-time positions, evening jobs, and weekend work.',
                'meta_title' => 'Part Time Jobs',
                'meta_description' => 'Browse part-time and flexible hour positions.',
                'icon' => 'job-categories/part-time.png',
                'is_active' => true,
                'sort_order' => 132,
            ],
            [
                'name' => 'Temporary',
                'slug' => Str::slug('Temporary'),
                'description' => 'Temporary positions, seasonal work, and short-term assignments.',
                'meta_title' => 'Temporary Jobs',
                'meta_description' => 'Find temporary and seasonal positions.',
                'icon' => 'job-categories/temporary.png',
                'is_active' => true,
                'sort_order' => 133,
            ],
            [
                'name' => 'Seasonal',
                'slug' => Str::slug('Seasonal'),
                'description' => 'Seasonal employment, holiday work, and peak-period positions.',
                'meta_title' => 'Seasonal Jobs',
                'meta_description' => 'Browse seasonal and holiday positions.',
                'icon' => 'job-categories/seasonal.png',
                'is_active' => true,
                'sort_order' => 134,
            ],
        ];

        foreach ($jobCategories as $category) {
            JobCategory::create($category);
        }

        $this->command->info('====================================');
        $this->command->info('JOB CATEGORY SEEDER COMPLETED SUCCESSFULLY!');
        $this->command->info('====================================');
        $this->command->info('Total job categories created: ' . count($jobCategories));
        $this->command->info('====================================');
    }
}